// Countries and the places inside them. Daily costs are rough budget-travel estimates in USD per person,
// as [budget bed (hostel or guesthouse), eating local, getting around, extras like entry fees, tours and permits].
// They are starting points for planning, not live prices. Last reviewed against 2026 prices in October 2026.
window.COUNTRIES = [
  { id: "vietnam", name: "Vietnam", region: "Southeast Asia", currency: "Vietnamese dong (VND)", best: [10, 11, 12, 1, 2, 3, 4],
    blurb: "Steaming pho on every corner, sleeper buses running the length of the country and some of the cheapest hostels and homestays in Asia. Vietnam on a budget is easy.",
    route: "Hanoi, then north to Ha Giang, then fly or bus south via Hoi An to Ho Chi Minh City. 3 to 4 weeks.",
    places: [
      { id: "hanoi", name: "Hanoi", d: [8, 9, 5, 5], tags: ["city", "food", "culture"],
        highlight: "Slurp bun cha on plastic stools in the Old Quarter, sip bia hoi on street corners, brave Train Street, then day trip to Ninh Binh.",
        tip: "Pho and bun cha cost about $2 a bowl at street food stalls. Grab bikes are cheaper than taxis and spare you the haggling." },
      { id: "ha-giang", name: "Ha Giang Loop", d: [8, 8, 10, 4], tags: ["mountains", "nature"],
        highlight: "Spend 3 to 4 days on a motorbike through limestone passes and the Ma Pi Leng gorge, sleeping in family homestays in minority villages.",
        tip: "Book an easy-rider driver if you have not ridden before. Homestays run about $8 a night including a home-cooked dinner and rice wine." },
      { id: "hoi-an", name: "Hoi An", d: [9, 9, 4, 5], tags: ["culture", "food", "beach"],
        highlight: "Lanterns glow over the yellow old town at night, tailors stitch cheap custom suits, and An Bang beach is a short bike ride away.",
        tip: "The old town ticket covers 5 sights, so pick your favorites. Rent a bicycle for about $1 a day from your guesthouse." },
      { id: "saigon", name: "Ho Chi Minh City", d: [9, 9, 5, 6], tags: ["city", "food", "history"],
        highlight: "Dodge a river of motorbikes, spend a sobering hour at the War Remnants Museum and reach the Mekong Delta by cheap local bus.",
        tip: "District 3 and Binh Thanh have cheaper street food and banh mi than touristy District 1, and they feel more local too." }
    ] },
  { id: "laos", name: "Laos", region: "Southeast Asia", currency: "Lao kip (LAK)", best: [11, 12, 1, 2, 3],
    blurb: "Slow river journeys, quiet mountain towns, cheap guesthouses and the most laid-back pace in Southeast Asia. Laos rewards travelers who are in no hurry.",
    route: "Slow boat from Huay Xai to Luang Prabang, north to Nong Khiaw, then south to Vang Vieng. 2 weeks.",
    places: [
      { id: "luang-prabang", name: "Luang Prabang", d: [10, 10, 5, 6], tags: ["culture", "nature"],
        highlight: "Watch the dawn alms procession of saffron-robed monks, swim below the Kuang Si waterfalls and catch sunset from the top of Mount Phousi.",
        tip: "The night market vegetarian buffet is about $2 a plate. Bike to Kuang Si if you are fit, or share a tuk-tuk." },
      { id: "nong-khiaw", name: "Nong Khiaw", d: [8, 8, 4, 4], tags: ["mountains", "trekking", "nature"],
        highlight: "Climb to karst viewpoints above the Nam Ou river at sunrise, then set off on multi-day treks to hill villages.",
        tip: "Riverside bungalows cost about the same as dorms elsewhere in Laos. Bring cash, since ATMs here are unreliable." },
      { id: "vang-vieng", name: "Vang Vieng", d: [8, 9, 5, 7], tags: ["nature", "trekking"],
        highlight: "Swim in the Blue Lagoons, explore caves and float down the Nam Song on a tube beneath towering limestone cliffs.",
        tip: "The new railway gets you here from Luang Prabang in about an hour, far quicker and more comfortable than the winding mountain road." }
    ] },
  { id: "thailand", name: "Thailand", region: "Southeast Asia", currency: "Thai baht (THB)", best: [11, 12, 1, 2],
    blurb: "The classic first big trip on a budget: easy transport, cheap guesthouses and hostels, legendary street food, tropical islands and misty northern mountains.",
    route: "Bangkok, night train to Chiang Mai, a loop through Pai, then down to the Andaman islands. 3 weeks.",
    places: [
      { id: "bangkok", name: "Bangkok", d: [13, 10, 6, 6], tags: ["city", "food", "culture"],
        highlight: "Hop between riverside temples by ferry, graze on street food in Chinatown at night and lose a morning in the weekend Chatuchak market.",
        tip: "Orange-flag river ferries cost under $1 and beat the traffic. Politely skip tuk-tuk drivers offering 'gem tours', which are a well-known scam." },
      { id: "chiang-mai", name: "Chiang Mai", d: [11, 10, 6, 6], tags: ["culture", "food", "mountains"],
        highlight: "Wander golden temples in the moated old city, eat khao soi at the Sunday walking street and ride a songthaew up to Doi Suthep.",
        tip: "Shared red songthaews cost about 30 baht around town. Avoid burning season in March and April, when smoke haze is heavy." },
      { id: "pai", name: "Pai", d: [11, 10, 5, 5], tags: ["mountains", "nature"],
        highlight: "After 762 curves of mountain road from Chiang Mai, you reach a relaxed valley of hot springs, canyon sunsets and waterfalls.",
        tip: "Rent a scooter only if you can already ride. Take motion sickness tablets before the minivan ride up from Chiang Mai." },
      { id: "koh-lanta", name: "Koh Lanta", d: [15, 12, 6, 6], tags: ["beach", "nature"],
        highlight: "Long, quiet beaches and laid-back bungalows, cheaper than Phi Phi, with snorkel trips out to the reefs of Koh Rok.",
        tip: "Stay on the west coast in shoulder season for half-price beach bungalows. Book snorkel trips locally rather than online." }
    ] },
  { id: "cambodia", name: "Cambodia", region: "Southeast Asia", currency: "US dollar and riel (KHR)", best: [11, 12, 1, 2, 3],
    blurb: "Angkor's temples, a sobering modern history, riverside capitals and a sleepy south coast, all with cheap guesthouses and simple street food.",
    route: "Siem Reap, bus to Phnom Penh, then down to Kampot. 10 to 14 days.",
    places: [
      { id: "siem-reap", name: "Siem Reap", d: [6, 8, 5, 12], tags: ["history", "culture"],
        highlight: "See Angkor Wat at sunrise and the jungle-wrapped roots of Ta Prohm, best explored at your own pace by bicycle.",
        tip: "The 3-day Angkor pass is $62 and works on any 3 days within 10 days, so you can rest between temple runs." },
      { id: "phnom-penh", name: "Phnom Penh", d: [7, 8, 5, 5], tags: ["city", "history"],
        highlight: "Tour the Royal Palace, browse riverside markets and learn the country's painful history at the Tuol Sleng and Choeung Ek memorials.",
        tip: "Use the PassApp ride app for fixed tuk-tuk fares. A bowl of street noodle soup is about $1.50 for breakfast." },
      { id: "kampot", name: "Kampot", d: [8, 8, 4, 4], tags: ["nature", "food"],
        highlight: "Lazy river sunsets, peppercorn farms in the countryside and a scooter ride up to the misty plateau of Bokor mountain.",
        tip: "Day trip to Kep for a crab market lunch instead of staying there, since Kampot has cheaper guesthouses and more choice." }
    ] },
  { id: "indonesia", name: "Indonesia", region: "Southeast Asia", currency: "Indonesian rupiah (IDR)", best: [5, 6, 7, 8, 9],
    blurb: "Volcano hikes, ancient temples, rice terraces and island-hopping across thousands of islands, with cheap warungs and homestays almost everywhere you go.",
    route: "Yogyakarta, overland to Bali, then east to Flores. 3 to 4 weeks.",
    places: [
      { id: "yogyakarta", name: "Yogyakarta", d: [8, 6, 5, 6], tags: ["culture", "history", "food"],
        highlight: "Explore Borobudur and Prambanan, Java's great temples, learn batik in local workshops and watch sunrise light up the Merapi volcano.",
        tip: "Gudeg, the local jackfruit stew, costs under $2 from street stalls. Book Borobudur tickets online in advance, as climbing slots are limited." },
      { id: "ubud", name: "Ubud, Bali", d: [11, 9, 6, 6], tags: ["culture", "nature"],
        highlight: "Walk through emerald rice terraces, catch temple ceremonies and start a 2 a.m. hike up Mount Batur to watch the sunrise.",
        tip: "Warungs off the main road are half the price of tourist cafes. Avoid the paid swing photo spots, which are overpriced." },
      { id: "labuan-bajo", name: "Labuan Bajo & Flores", d: [12, 9, 6, 15], tags: ["beach", "nature"],
        highlight: "Take boat trips to see Komodo dragons, snorkel off Pink Beach and swim with manta rays in Komodo National Park.",
        tip: "Shared 2-day boat trips beat day tours on value. Park fees are high, so budget for them before you book." }
    ] },
  { id: "nepal", name: "Nepal", region: "South Asia", currency: "Nepalese rupee (NPR)", best: [3, 4, 10, 11],
    blurb: "The cheapest big-mountain trekking in the world, walking teahouse to teahouse under Himalayan peaks, with dal bhat refills and cheap guesthouses in Kathmandu and Pokhara.",
    route: "Kathmandu, bus to Pokhara, then the Annapurna Circuit. 3 to 4 weeks.",
    places: [
      { id: "kathmandu", name: "Kathmandu", d: [7, 8, 4, 4], tags: ["city", "culture", "history"],
        highlight: "Wander the temple-filled Durbar squares, circle Boudhanath stupa with spinning prayer wheels and kit out for your trek in Thamel.",
        tip: "Buy or rent trekking gear in Thamel instead of bringing it from home. Dal bhat comes with free refills, so one plate is a full meal." },
      { id: "pokhara", name: "Pokhara", d: [8, 9, 4, 5], tags: ["nature", "mountains"],
        highlight: "Lakeside cafes, sunrise over the Annapurnas from Sarangkot and paragliding above Phewa Lake make this the easiest place to unwind after a trek.",
        tip: "Tourist buses from Kathmandu are about $10. Rent a rowboat on the lake for a few dollars instead of a guided trip." },
      { id: "annapurna", name: "Annapurna Circuit", d: [5, 14, 2, 6], tags: ["trekking", "mountains"],
        highlight: "Walk 12 to 18 days through Gurung villages and high desert, crossing the Thorong La pass at 5,416 m.",
        tip: "Teahouse rooms are often free if you eat dinner and breakfast there. A licensed guide is officially required, though checks vary along the route." }
    ] },
  { id: "india", name: "India", region: "South Asia", currency: "Indian rupee (INR)", best: [10, 11, 12, 1, 2, 3],
    blurb: "Overwhelming, endlessly varied and very cheap, from Rajasthan's forts to Himalayan valleys, with sleeper trains, street food and budget hostels linking it all.",
    route: "Jaipur and Udaipur in Rajasthan, then Varanasi and up to Rishikesh. 3 to 4 weeks.",
    places: [
      { id: "jaipur", name: "Jaipur", d: [7, 6, 5, 5], tags: ["culture", "history", "food"],
        highlight: "Climb to Amber Fort, gaze up at the honeycomb Hawa Mahal and bargain for textiles in the bazaars of the Pink City.",
        tip: "The composite ticket covers several forts and monuments for less. Use Uber autos to avoid haggling with rickshaw drivers." },
      { id: "udaipur", name: "Udaipur", d: [8, 6, 4, 4], tags: ["culture", "history"],
        highlight: "Lake palaces, rooftop sunsets over Lake Pichola and a day trip to the vast walls of Kumbhalgarh fort.",
        tip: "Rooftop hostels on the lake cost the same as ones without the view, so hold out for a lakeside bed." },
      { id: "varanasi", name: "Varanasi", d: [6, 5, 4, 3], tags: ["culture", "history"],
        highlight: "Drift past the ghats on a dawn boat ride, then join the crowds for the fire-lit evening Ganga aarti ceremony.",
        tip: "Agree boat prices before you board. Lassi shops near the ghats make a cheap, filling lunch." },
      { id: "rishikesh", name: "Rishikesh", d: [7, 6, 3, 3], tags: ["mountains", "nature", "culture"],
        highlight: "Practice yoga by the Ganges, raft its rapids and hike through Himalayan foothills to waterfalls and temples above town.",
        tip: "Many ashrams offer cheap stays with simple meals included. The town is vegetarian and alcohol-free, which keeps spending low." }
    ] },
  { id: "sri-lanka", name: "Sri Lanka", region: "South Asia", currency: "Sri Lankan rupee (LKR)", best: [12, 1, 2, 3, 4],
    blurb: "Tea country train rides, ancient cities, surf beaches and wildlife on a compact island where cheap guesthouses and rice and curry are never far away.",
    route: "Kandy, train to Ella, then down to Mirissa. 2 weeks.",
    places: [
      { id: "kandy", name: "Kandy", d: [10, 9, 4, 8], tags: ["culture", "history"],
        highlight: "Visit the Temple of the Tooth on the lake, then board the famous hill-country railway toward the tea plantations.",
        tip: "Rice and curry from local 'hotels', the island's simple canteens, costs about $2 for a heaped plate." },
      { id: "ella", name: "Ella", d: [11, 9, 3, 4], tags: ["nature", "trekking", "mountains"],
        highlight: "Watch a blue train cross the Nine Arches Bridge, then hike Little Adam's Peak for sunrise over tea-covered hills.",
        tip: "Unreserved second class on the Kandy to Ella train is under $2. Sit on the right side for the best views." },
      { id: "mirissa", name: "Mirissa", d: [13, 10, 4, 5], tags: ["beach"],
        highlight: "Surf breaks for beginners, whale watching boat trips and sunset from Coconut Tree Hill on the south coast.",
        tip: "Local buses along the coast cost a fraction of tuk-tuk prices and run often between beach towns." }
    ] },
  { id: "kyrgyzstan", name: "Kyrgyzstan", region: "Central Asia", currency: "Kyrgyz som (KGS)", best: [6, 7, 8, 9],
    blurb: "Wild alpine lakes, nomad yurts, horse treks and free camping almost anywhere, with cheap guesthouses and some of the best hiking in Central Asia.",
    route: "Bishkek, east to Karakol for treks, then a yurt stay at Song-Kul. 2 to 3 weeks.",
    places: [
      { id: "bishkek", name: "Bishkek", d: [9, 8, 3, 3], tags: ["city", "food"],
        highlight: "Haggle in Osh Bazaar, admire Soviet-era architecture and take an easy day trip to hike in Ala Archa national park.",
        tip: "Plov and lagman cost about $3 at local cafes. Marshrutka minibuses go everywhere in the city for 20 som." },
      { id: "karakol", name: "Karakol & Ala-Kul", d: [8, 8, 4, 4], tags: ["trekking", "mountains", "nature"],
        highlight: "The 3-day Ala-Kul trek climbs to a turquoise lake at 3,560 m, then descends to the hot springs of Altyn-Arashan.",
        tip: "Camping is free and widely accepted. Rent tents and stoves at the Karakol tourist office instead of buying gear." },
      { id: "song-kul", name: "Song-Kul Lake", d: [18, 4, 8, 4], tags: ["nature", "mountains"],
        highlight: "Sleep in a family yurt beside a high alpine lake, ride horses across summer pastures and drink fresh kumis with herders.",
        tip: "Yurt stays include dinner and breakfast, so your food costs drop to almost nothing while you are here." }
    ] },
  { id: "georgia", name: "Georgia", region: "Europe & Caucasus", currency: "Georgian lari (GEL)", best: [5, 6, 7, 8, 9],
    blurb: "Caucasus peaks, cheap natural wine, cheesy khachapuri and guesthouses run by famously generous hosts. Georgia on a budget is one of Europe's best deals.",
    route: "Tbilisi, up the Military Highway to Kazbegi, then west to Svaneti. 2 weeks.",
    places: [
      { id: "tbilisi", name: "Tbilisi", d: [11, 10, 3, 6], tags: ["city", "food", "culture"],
        highlight: "Soak in the domed sulfur baths, wander old town streets of carved wooden balconies and drink natural wine in Sololaki's bars.",
        tip: "The metro is about $0.40 a ride. Khachapuri, the cheese-filled bread, is a full meal on its own." },
      { id: "kazbegi", name: "Kazbegi", d: [12, 10, 4, 3], tags: ["mountains", "trekking"],
        highlight: "Hike up to Gergeti Trinity Church beneath snowy Mount Kazbek, then walk the quiet Truso valley past mineral springs.",
        tip: "A shared marshrutka from Tbilisi costs about $5 along the scenic Georgian Military Highway." },
      { id: "mestia", name: "Mestia & Ushguli", d: [13, 11, 6, 4], tags: ["trekking", "mountains", "history"],
        highlight: "Medieval stone defense towers rise above Svaneti villages on the 4-day Mestia to Ushguli trek, one of the Caucasus' finest hikes.",
        tip: "Guesthouses along the trek include dinner. Take the night train to Zugdidi to save the cost of a bed." }
    ] },
  { id: "albania", name: "Albania", region: "Europe & Caucasus", currency: "Albanian lek (ALL)", best: [5, 6, 9, 10],
    blurb: "Europe's cheapest coastline and some of its wildest mountains, with Ottoman towns, byrek bakeries and family guesthouses that make Albania easy on a budget.",
    route: "Tirana, north to Theth for the pass hike, then Berat and the Riviera. 2 weeks.",
    places: [
      { id: "tirana", name: "Tirana", d: [15, 13, 4, 4], tags: ["city", "history", "food"],
        highlight: "Wander colorfully painted apartment blocks, explore the Cold War Bunk'Art museums and ride the cable car up Mount Dajti.",
        tip: "Byrek from bakeries is under $1. City buses cost about 40 lek, so skip taxis for short hops." },
      { id: "theth", name: "Theth & Valbona", d: [28, 7, 11, 2], tags: ["trekking", "mountains", "nature"],
        highlight: "Hike the Valbona to Theth pass through the Accursed Mountains, a full day of limestone peaks, beech forest and shepherd huts.",
        tip: "Guesthouses include dinner and breakfast for about $30. Book the ferry over Koman Lake to start the classic loop." },
      { id: "berat", name: "Berat", d: [14, 13, 4, 3], tags: ["history", "culture"],
        highlight: "Known as the 'town of a thousand windows', with white Ottoman houses below a castle where people still live.",
        tip: "Local wineries do tastings for a few dollars, a cheap way to try Albanian wine." },
      { id: "himare", name: "Himarë", d: [17, 16, 5, 4], tags: ["beach"],
        highlight: "Clear water coves and pebble beaches on the Albanian Riviera, cheaper and calmer than busy Ksamil.",
        tip: "Come in June or September for half-price rooms and empty beaches, when the sea is still warm." }
    ] },
  { id: "poland", name: "Poland", region: "Europe & Caucasus", currency: "Polish złoty (PLN)", best: [5, 6, 7, 8, 9],
    blurb: "Big-city culture, mountain hikes and Baltic beaches at a fraction of Western European prices, with cheap hostels, pierogi and milk bars.",
    route: "Kraków, a few days hiking from Zakopane, then north to Gdańsk by train. 10 days.",
    places: [
      { id: "krakow", name: "Kraków", d: [20, 15, 5, 8], tags: ["city", "history", "food"],
        highlight: "Stroll the grand old town square, eat pierogi in the Jewish quarter of Kazimierz and day trip to the Wieliczka salt mine.",
        tip: "Milk bars serve hot lunches for under $6. Free walking tours run daily from the main square." },
      { id: "zakopane", name: "Zakopane", d: [22, 15, 6, 4], tags: ["mountains", "trekking"],
        highlight: "Hike in the Tatra Mountains to the glacial lake of Morskie Oko and over the ridge into Slovakia.",
        tip: "Mountain huts serve cheap soup and hot drinks. Buses from Kraków are about $6 and leave often." },
      { id: "gdansk", name: "Gdańsk", d: [22, 16, 6, 6], tags: ["city", "history", "beach"],
        highlight: "Walk the rebuilt Hanseatic old town, learn the story of the Solidarity movement and spend afternoons on Baltic beaches.",
        tip: "A cheap train ride takes you to the sandy beach and wooden pier at Sopot." }
    ] },
  { id: "morocco", name: "Morocco", region: "Africa & Middle East", currency: "Moroccan dirham (MAD)", best: [3, 4, 5, 10, 11],
    blurb: "Labyrinthine medinas, Atlas mountain hikes and Saharan dunes within a few cheap bus rides of each other, with riad hostels and mint tea at every stop.",
    route: "Marrakech, up to Imlil for Toubkal, across to Merzouga, then north to Chefchaouen. 2 to 3 weeks.",
    places: [
      { id: "marrakech", name: "Marrakech", d: [12, 10, 4, 7], tags: ["city", "culture", "food"],
        highlight: "Sleep in a riad hostel inside the medina, then eat grilled meats and snail soup at the night food stalls on Jemaa el-Fnaa.",
        tip: "Agree prices before you sit down at a food stall. A bowl of harira soup is about $0.50." },
      { id: "imlil", name: "Imlil & Toubkal", d: [13, 11, 8, 15], tags: ["trekking", "mountains"],
        highlight: "Climb Toubkal over 2 days, at 4,167 m the highest peak in North Africa, starting from a Berber mountain village.",
        tip: "A guide is required for Toubkal, so share one with other hikers to split the cost. Refuges sell meals and bunks." },
      { id: "merzouga", name: "Merzouga", d: [13, 9, 12, 25], tags: ["nature"],
        highlight: "Ride a camel into the towering Erg Chebbi dunes at sunset and spend a night in a Saharan desert camp under the stars.",
        tip: "Book the camp directly in Merzouga rather than a tour from Marrakech, which adds long drive days and markup." },
      { id: "chefchaouen", name: "Chefchaouen", d: [12, 9, 4, 3], tags: ["culture", "trekking"],
        highlight: "Wander the blue-washed lanes of a Rif mountain town, then day hike to the pools of the Akchour waterfalls.",
        tip: "CTM buses are reliable and cheap. Book a day ahead in high season, since seats sell out." }
    ] },
  { id: "peru", name: "Peru", region: "Latin America", currency: "Peruvian sol (PEN)", best: [5, 6, 7, 8, 9],
    blurb: "Inca ruins, high Andes treks and some of the best food in South America, with menu del día lunches and cheap hostels keeping Peru affordable on a budget.",
    route: "Arequipa, a stop in Huacachina, then Cusco and the Salkantay trek. 3 weeks.",
    places: [
      { id: "cusco", name: "Cusco", d: [12, 11, 4, 8], tags: ["history", "culture", "mountains"],
        highlight: "Run your hands over Inca stonework, explore the Sacred Valley and take a day trip to the striped slopes of Rainbow Mountain.",
        tip: "Menu del día lunches are about $3. Spend 2 days acclimatising before trekking to avoid altitude sickness." },
      { id: "salkantay", name: "Salkantay Trek", d: [20, 16, 4, 14], tags: ["trekking", "mountains"],
        highlight: "Hike 5 days over a 4,600 m pass beneath glaciers, through cloud forest to Machu Picchu, with no permit lottery.",
        tip: "Tours run about $250 all-in. It is half the price of the Inca Trail and needs no booking months ahead." },
      { id: "arequipa", name: "Arequipa", d: [12, 10, 3, 5], tags: ["city", "food", "trekking"],
        highlight: "Explore the white volcanic stone of the old city and Santa Catalina monastery, then trek deep into Colca Canyon to spot condors.",
        tip: "Do Colca Canyon on your own by public bus to Cabanaconde, and stay in cheap guesthouses in the canyon." },
      { id: "huacachina", name: "Huacachina", d: [13, 10, 4, 8], tags: ["nature"],
        highlight: "A palm-ringed desert oasis surrounded by giant dunes, with sandboarding and dune buggy rides at sunset.",
        tip: "Stay in nearby Ica for cheaper food and beds. Buggy tours are about $15 including a board." }
    ] },
  { id: "bolivia", name: "Bolivia", region: "Latin America", currency: "Bolivian boliviano (BOB)", best: [4, 5, 6, 7, 8, 9, 10],
    blurb: "The cheapest country in South America, with high-altitude cities, the Uyuni salt flat, Amazon jungle and $2 market lunches.",
    route: "La Paz, Sucre, then the Uyuni jeep tour across to Chile. 2 weeks.",
    places: [
      { id: "la-paz", name: "La Paz", d: [9, 8, 3, 5], tags: ["city", "culture"],
        highlight: "Glide over the city by cable car, browse the witches' market for dried llama fetuses and cycle Death Road down to the jungle.",
        tip: "Mi Teleférico cable cars cost about $0.50 a ride. Market lunches are $2 for soup and a main course." },
      { id: "sucre", name: "Sucre", d: [9, 7, 2, 3], tags: ["city", "history"],
        highlight: "A white colonial capital with cheap Spanish schools, leafy plazas and real dinosaur tracks on a quarry wall outside town.",
        tip: "A good place to take a week of Spanish classes on a budget, with homestays that include meals." },
      { id: "uyuni", name: "Uyuni Salt Flat", d: [15, 10, 25, 7], tags: ["nature"],
        highlight: "The 3-day jeep tour crosses the blinding white salt flat to red and green flamingo lagoons near the Chilean border.",
        tip: "Compare agencies in Uyuni town before booking. 3-day tours run $150 to $200 all-in, including meals and basic lodging." }
    ] },
  { id: "guatemala", name: "Guatemala", region: "Latin America", currency: "Guatemalan quetzal (GTQ)", best: [11, 12, 1, 2, 3, 4],
    blurb: "Smoking volcanoes, Mayan ruins and lake villages linked by colorful chicken buses, with cheap Spanish schools and hostels all along the way.",
    route: "Antigua, Lake Atitlán, then north to Flores for Tikal. 2 weeks.",
    places: [
      { id: "antigua", name: "Antigua", d: [13, 10, 4, 6], tags: ["culture", "history", "trekking"],
        highlight: "Wander cobbled streets of colonial ruins, then do the overnight Acatenango hike to watch Volcán de Fuego erupt beside you.",
        tip: "Acatenango tours run about $60 with gear. Rent warm clothes in town, since it freezes at the top." },
      { id: "atitlan", name: "Lake Atitlán", d: [12, 10, 5, 4], tags: ["nature", "culture"],
        highlight: "Hop between San Pedro, San Marcos and San Juan by lancha across a volcano-ringed lake, each village with its own character.",
        tip: "Pay local prices on boats by asking another passenger what they paid first, then hand over exact change." },
      { id: "flores", name: "Flores & Tikal", d: [13, 10, 5, 12], tags: ["history", "nature"],
        highlight: "Stay on a tiny island town in Lake Petén Itzá, then watch sunrise over the jungle temples of Tikal while howler monkeys roar.",
        tip: "Take the public colectivo to Tikal instead of a tour, and hire a guide at the gate if you want one." }
    ] },
  { id: "mexico", name: "Mexico", region: "Latin America", currency: "Mexican peso (MXN)", best: [10, 11, 12, 1, 2, 3],
    blurb: "World-class food at street prices, ancient pyramids, colonial towns and comfortable night buses everywhere, making Mexico one of the easiest countries to travel on a budget.",
    route: "Mexico City, Oaxaca, then San Cristóbal de las Casas. 2 to 3 weeks.",
    places: [
      { id: "cdmx", name: "Mexico City", d: [18, 14, 5, 6], tags: ["city", "food", "culture"],
        highlight: "Graze at taco stands, spend a day in the National Anthropology Museum and climb the pyramids at Teotihuacán on a day trip.",
        tip: "The metro costs 5 pesos a ride. Street tacos are far cheaper than sit-down restaurants and often better." },
      { id: "oaxaca", name: "Oaxaca", d: [16, 13, 6, 6], tags: ["food", "culture"],
        highlight: "Mole, mezcal and buzzing markets in the city, plus day trips to the petrified waterfalls of Hierve el Agua and Monte Albán.",
        tip: "Eat in the Mercado 20 de Noviembre grill hall. ADO night buses save a hostel night between cities." },
      { id: "san-cristobal", name: "San Cristóbal de las Casas", d: [14, 12, 6, 4], tags: ["culture", "mountains"],
        highlight: "A cool highland town of colorful colonial streets, with indigenous Tzotzil villages and the cliffs of Sumidero Canyon nearby.",
        tip: "Colectivos to nearby villages cost about $1. Bring layers, since nights get cold at this altitude." }
    ] },
  { id: "colombia", name: "Colombia", region: "Latin America", currency: "Colombian peso (COP)", best: [12, 1, 2, 3, 7, 8],
    blurb: "Friendly cities, coffee country, cloud forest and the Caribbean coast at budget prices, with good hostels and filling set lunches almost everywhere.",
    route: "Medellín and Guatapé, south to Salento, then fly to Cartagena. 3 weeks.",
    places: [
      { id: "medellin", name: "Medellín", d: [14, 11, 4, 6], tags: ["city", "culture"],
        highlight: "Ride the Metrocable over hillside barrios and join a guided Comuna 13 graffiti walk to hear how the city transformed.",
        tip: "One cheap ticket covers metro and metrocable. A bandeja paisa fills you up for the whole day." },
      { id: "guatape", name: "Guatapé", d: [15, 11, 5, 3], tags: ["nature"],
        highlight: "Climb 740 steps up El Peñol rock for a view over a maze of blue lakes, then wander the brightly painted town below.",
        tip: "Buses leave Medellín's north terminal every half hour, so it is an easy and cheap day trip from Medellín." },
      { id: "salento", name: "Salento", d: [13, 10, 4, 5], tags: ["nature", "trekking"],
        highlight: "Hike among towering wax palms in the Cocora valley and tour coffee farms in the green hills of the coffee region.",
        tip: "Willys jeeps to Cocora leave from the main square and cost about $2 each way." },
      { id: "cartagena", name: "Cartagena", d: [17, 14, 5, 6], tags: ["beach", "history", "city"],
        highlight: "Wander the walled old city's colorful balconies, find street art in Getsemaní and take boat day trips to the Rosario islands.",
        tip: "Stay in Getsemaní for cheaper hostels. Book island boats directly at the dock instead of through street touts." }
    ] },
  { id: "argentina", name: "Argentina", region: "Latin America", currency: "Argentine peso (ARS)", best: [11, 12, 1, 2, 3],
    blurb: "Steak, Malbec and Patagonia, with some of the best hiking on Earth and free trails from town, though no longer cheap in dollars.",
    route: "Buenos Aires, Mendoza, then fly south to El Chaltén. 3 weeks.",
    places: [
      { id: "buenos-aires", name: "Buenos Aires", d: [20, 19, 5, 6], tags: ["city", "food", "culture"],
        highlight: "Browse the San Telmo Sunday market, watch tango in the street and eat late-night steak at neighborhood parrillas.",
        tip: "Prices change fast with inflation. Check current exchange options, such as cards and transfer services, before you go." },
      { id: "mendoza", name: "Mendoza", d: [19, 18, 6, 8], tags: ["food", "nature"],
        highlight: "Cycle between Malbec wineries in the sun with the snowy Andes rising behind the vineyards.",
        tip: "Rent bikes in Maipú and visit 3 or 4 wineries in a day instead of paying for a tour." },
      { id: "el-chalten", name: "El Chaltén", d: [28, 23, 5, 22], tags: ["trekking", "mountains", "nature"],
        highlight: "Trails start straight from town and climb to Laguna de los Tres, the glacial lake beneath the granite spires of Fitz Roy.",
        tip: "Since late 2024 the park charges foreigners about $40 a day for trails, with multi-day passes cheaper. Carry food from El Calafate; town shops are pricey." }
    ] },
  { id: "egypt", name: "Egypt", region: "Africa & Middle East", currency: "Egyptian pound (EGP)", best: [10, 11, 12, 1, 2, 3, 4],
    blurb: "Pharaonic temples, Red Sea reefs and remote desert oases, with cheap koshari, sleeper trains and some of the lowest prices around the Mediterranean.",
    route: "Cairo, sleeper train to Luxor and Aswan, back north to Dahab, then a long bus west to Siwa. 3 weeks.",
    places: [
      { id: "cairo", name: "Cairo & Giza", d: [10, 7, 3, 15], tags: ["city", "history", "food"],
        highlight: "Stand before the Giza pyramids, see Tutankhamun's treasures at the Grand Egyptian Museum and eat koshari in Islamic Cairo's old lanes.",
        tip: "Use Uber instead of street taxis to avoid haggling. Koshari, the national comfort food, costs about $1 a bowl." },
      { id: "luxor", name: "Luxor", d: [9, 6, 3, 18], tags: ["history", "culture"],
        highlight: "Walk among Karnak's giant columns, descend into painted tombs in the Valley of the Kings and drift over the West Bank by dawn balloon.",
        tip: "Cross the Nile on the public ferry for a few cents. Entry tickets add up quickly, so pick your temples." },
      { id: "aswan", name: "Aswan", d: [9, 6, 3, 12], tags: ["culture", "nature"],
        highlight: "Sail the Nile by felucca at sunset and wander the colorfully painted Nubian villages on Elephantine Island.",
        tip: "Sleep in a Nubian guesthouse on the west bank. Abu Simbel is a long but worthwhile day trip from here." },
      { id: "dahab", name: "Dahab", d: [10, 8, 2, 8], tags: ["beach", "nature", "trekking"],
        highlight: "A laid-back Red Sea town where you snorkel coral reefs straight from the shore and climb Mount Sinai for sunrise.",
        tip: "Snorkel the Lighthouse and Eel Garden reefs for free. Dive courses here are among the cheapest anywhere in the world." },
      { id: "siwa", name: "Siwa Oasis", d: [12, 7, 5, 8], tags: ["offbeat", "nature", "culture"],
        highlight: "A Berber oasis near the Libyan border, with salt lakes to float in, mud-brick ruins and hot springs beside the Great Sand Sea.",
        tip: "Get around by bicycle. Overnight buses from Cairo or Alexandria take 8 to 10 hours, and checkpoints need your passport." },
      { id: "white-desert", name: "White Desert", d: [15, 6, 10, 20], tags: ["offbeat", "nature"],
        highlight: "Wind-carved chalk formations rise from the sand like giant mushrooms, with a night camped under the stars near Farafra.",
        tip: "Book a 1 or 2 night jeep trip from Bahariya Oasis. Bring warm layers, since desert nights are cold." }
    ] },
  { id: "jordan", name: "Jordan", region: "Africa & Middle East", currency: "Jordanian dinar (JOD)", best: [3, 4, 5, 10, 11],
    blurb: "Rose-red Petra, Mars-like Wadi Rum and a long-distance hiking trail that crosses the whole country, with falafel stands and Bedouin camps along the way.",
    route: "Amman, the Dead Sea, Dana, then hike or bus to Petra and finish in Wadi Rum. 10 days.",
    places: [
      { id: "amman", name: "Amman", d: [16, 12, 4, 6], tags: ["city", "food", "history"],
        highlight: "Climb to the Citadel for city views, sit in the Roman theatre and eat falafel at Hashem, a downtown institution.",
        tip: "Buy the Jordan Pass before you arrive. It covers your visa and Petra entry, which saves a lot." },
      { id: "petra", name: "Petra", d: [18, 15, 4, 22], tags: ["history", "trekking"],
        highlight: "Walk the Siq to the Treasury, climb the 800 steps to the Monastery and hike the quieter back trail from Little Petra.",
        tip: "Get a 2 or 3 day Petra ticket through the Jordan Pass. Arrive at 6 a.m. for an empty Siq." },
      { id: "wadi-rum", name: "Wadi Rum", d: [22, 8, 8, 10], tags: ["nature", "trekking"],
        highlight: "Explore sandstone canyons and red dunes by jeep or on foot, then sleep in a Bedouin camp under a sky full of stars.",
        tip: "Camp prices often include dinner and breakfast. Book a jeep tour directly with a local Bedouin camp to avoid agency markups." },
      { id: "dana", name: "Dana Biosphere Reserve", d: [20, 10, 6, 6], tags: ["offbeat", "trekking", "nature"],
        highlight: "A stone village perched on a canyon rim, and a full-day hike down Wadi Dana through changing landscapes toward Feynan.",
        tip: "Stay at the Dana guesthouse in the village. The Jordan Trail passes through here on its way to Petra." }
    ] },
  { id: "tunisia", name: "Tunisia", region: "Africa & Middle East", currency: "Tunisian dinar (TND)", best: [3, 4, 5, 10, 11],
    blurb: "Roman ruins, Saharan oases and blue-and-white villages, with cheap couscous, shared louages and far fewer tourists than Morocco.",
    route: "Tunis and Carthage, El Jem, the Saharan south around Tozeur, then Djerba. 2 weeks.",
    places: [
      { id: "tunis", name: "Tunis & Sidi Bou Said", d: [14, 8, 3, 6], tags: ["city", "history", "culture"],
        highlight: "Wander the medina's souks, see the Bardo's Roman mosaics, explore the ruins of Carthage and photograph the blue doors of Sidi Bou Said.",
        tip: "The TGM light rail runs from Tunis to Carthage and Sidi Bou Said for under $1, so skip the taxis." },
      { id: "tozeur", name: "Tozeur & Chebika", d: [13, 7, 6, 6], tags: ["offbeat", "nature"],
        highlight: "Palm oases, the shimmering Chott el Djerid salt lake and the mountain oases of Chebika and Tamerza with their waterfalls and canyons.",
        tip: "Share a 4x4 with other travelers to visit the mountain oases and Star Wars filming sets, and split the cost." },
      { id: "matmata", name: "Matmata", d: [14, 7, 5, 4], tags: ["offbeat", "culture"],
        highlight: "Troglodyte Berber homes are dug deep into the ground here, and one of them served as Luke Skywalker's childhood home.",
        tip: "Sleep in an underground guesthouse for a cheap, memorable night. Louages (shared taxis) connect it to Gabès." },
      { id: "djerba", name: "Djerba", d: [15, 9, 3, 4], tags: ["beach", "culture"],
        highlight: "Island beaches, open-air street art in the village of Erriadh and the ancient El Ghriba synagogue.",
        tip: "Rent a bicycle or scooter to get around the flat island. Houmt Souk has the cheapest food." }
    ] },
  { id: "ethiopia", name: "Ethiopia", region: "Africa & Middle East", currency: "Ethiopian birr (ETB)", best: [10, 11, 12, 1, 2],
    advisory: "Several governments, including the UK, advise against all travel to the Amhara region, home to Lalibela, Gondar, Bahir Dar and the Simien Mountains, because of armed conflict. Flights to Tigray are suspended, and restrictions can change at short notice.",
    blurb: "Rock-hewn churches, highland trekking and coffee ceremonies unlike anywhere else in Africa. Parts of the country are under travel warnings, so check current advice before planning a route.",
    route: "Addis Ababa, Harar, then south to the Bale Mountains and the Omo Valley. The northern circuit via Gondar, the Simien Mountains and Lalibela is off-limits while conflict continues. 2 weeks.",
    places: [
      { id: "addis", name: "Addis Ababa", d: [12, 6, 3, 4], tags: ["city", "food", "culture"],
        highlight: "Browse Merkato, one of Africa's biggest open-air markets, meet the Lucy fossil at the National Museum and join a street coffee ceremony.",
        tip: "Injera with shiro, a spiced chickpea stew, is a filling lunch for a couple of dollars." },
      { id: "lalibela", name: "Lalibela", d: [14, 7, 3, 20], tags: ["history", "culture"],
        highlight: "Eleven medieval churches carved straight down into the rock, still used for worship by Orthodox pilgrims today.",
        tip: "Lalibela is in Amhara, where several governments advise against all travel. Check current advice; if visits resume, festivals like Timkat need early bookings." },
      { id: "simien", name: "Simien Mountains", d: [10, 8, 6, 20], tags: ["trekking", "mountains"],
        highlight: "Multi-day treks along sheer escarpment edges, with gelada monkeys grazing beside the trail and views across jagged highland peaks.",
        tip: "This park is in Amhara, under current travel warnings, so check advice first. A park scout is required, and Debark arranges treks cheaper than Gondar agencies." },
      { id: "danakil", name: "Danakil Depression", d: [15, 8, 15, 25], tags: ["offbeat", "nature"],
        highlight: "Neon sulfur springs at Dallol and the Erta Ale lava lake, in one of the hottest places on Earth.",
        tip: "Only possible on an organised tour from Mekele. Check current safety advice for the Afar region before booking anything." }
    ] },
  { id: "madagascar", name: "Madagascar", region: "Africa & Middle East", currency: "Malagasy ariary (MGA)", best: [4, 5, 9, 10, 11],
    blurb: "Lemurs, baobabs and wildlife found nowhere else on Earth, reached by long, bumpy taxi-brousse rides and rewarded with cheap guesthouses and rice dishes.",
    route: "Antananarivo, east to Andasibe, then the long road south through Ranomafana and Isalo. 3 weeks.",
    places: [
      { id: "andasibe", name: "Andasibe", d: [12, 7, 4, 12], tags: ["nature", "offbeat"],
        highlight: "Hear the haunting call of the indri, the largest lemur, echo through the rainforest, then spot chameleons on a night walk.",
        tip: "Hire a local guide at the park gate. Night walks on the road outside the park cost less than inside." },
      { id: "morondava", name: "Morondava & Avenue of the Baobabs", d: [12, 7, 8, 6], tags: ["offbeat", "nature"],
        highlight: "Giant baobabs line a red dirt road glowing at sunset, with the Tsingy limestone needles further north.",
        tip: "Share a taxi-brousse from Antsirabe to save money. Roads to the Tsingy are only open in the dry season." },
      { id: "isalo", name: "Isalo National Park", d: [12, 7, 4, 15], tags: ["trekking", "nature"],
        highlight: "Hike through sandstone canyons to natural swimming pools, with ring-tailed lemurs leaping through the trees above.",
        tip: "Ranohira village has cheap guesthouses. Guides are mandatory and priced per circuit, so join other hikers to share." },
      { id: "ranomafana", name: "Ranomafana", d: [11, 7, 4, 12], tags: ["nature", "trekking"],
        highlight: "Misty cloud forest home to the rare golden bamboo lemur, with hot springs to soak in back in the village.",
        tip: "Go early in the morning for the best lemur sightings, and book guides at the park office." }
    ] },
  { id: "malawi", name: "Malawi", region: "Africa & Middle East", currency: "Malawian kwacha (MWK)", best: [5, 6, 7, 8, 9, 10],
    blurb: "The 'warm heart of Africa', with a freshwater lake as big as a sea, cheap lakeside lodges and few other travelers.",
    route: "Lilongwe, Cape Maclear, up the lake to Nkhata Bay, with Zomba Plateau on the way. 2 weeks.",
    places: [
      { id: "cape-maclear", name: "Cape Maclear", d: [10, 7, 4, 6], tags: ["beach", "nature", "offbeat"],
        highlight: "Snorkel among colorful cichlid fish in clear lake water and kayak to uninhabited islands for a night of camping.",
        tip: "Lakeside lodges offer camping for a few dollars, and fresh fish dinners are cheap in the village." },
      { id: "nkhata-bay", name: "Nkhata Bay", d: [9, 7, 3, 4], tags: ["beach", "offbeat"],
        highlight: "Cliff jumping into clear water and lazy hammock days in a hilly bay on the northern shore of Lake Malawi.",
        tip: "The Ilala ferry runs up and down the lake weekly, but check its schedule before planning around it." },
      { id: "zomba", name: "Zomba Plateau", d: [9, 6, 3, 3], tags: ["offbeat", "trekking", "mountains"],
        highlight: "Walk through pine forests to waterfalls and viewpoints high over the southern plains, a cool escape from the lowland heat.",
        tip: "Fresh strawberries from roadside sellers are a cheap local treat. Campsites and simple lodges sit on the plateau." }
    ] },
  { id: "philippines", name: "Philippines", region: "Southeast Asia", currency: "Philippine peso (PHP)", best: [12, 1, 2, 3, 4, 5],
    blurb: "Over 7,000 islands of limestone lagoons, surf breaks, white sand beaches and mountain rice terraces, with cheap island-hopping tours and homestays.",
    route: "Fly into Manila, north to Batad, then island-hop Palawan, Siquijor and Siargao. 3 to 4 weeks.",
    places: [
      { id: "el-nido", name: "El Nido", d: [14, 10, 5, 15], tags: ["beach", "nature"],
        highlight: "Island-hop through limestone lagoons and secret beaches in the Bacuit archipelago, snorkeling over coral between towering cliffs.",
        tip: "Shared boat tours A to D have fixed prices. Take the multi-day expedition boat to Coron for island camping." },
      { id: "siargao", name: "Siargao", d: [13, 10, 5, 6], tags: ["beach", "nature"],
        highlight: "Surf the famous Cloud 9 break, swim in the rock pools at Magpupungko and island hop to sandbars and lagoons.",
        tip: "Rent a scooter to explore the island. Surf lessons with a board cost about $10." },
      { id: "batad", name: "Batad Rice Terraces", d: [10, 8, 6, 3], tags: ["offbeat", "trekking", "mountains"],
        highlight: "A 2,000-year-old amphitheatre of rice terraces carved into the mountains and reached only on foot.",
        tip: "Take the overnight bus from Manila to Banaue. Homestays sit right on the terraces with views from your bed." },
      { id: "siquijor", name: "Siquijor", d: [12, 8, 4, 3], tags: ["offbeat", "beach"],
        highlight: "A small 'mystic island' known for its folk healers, with waterfalls, quiet beaches and coral reefs to snorkel.",
        tip: "Circle the island by scooter in a day. Cambugahay Falls is free with a small donation." }
    ] },
  { id: "malaysia", name: "Malaysia", region: "Southeast Asia", currency: "Malaysian ringgit (MYR)", best: [3, 4, 5, 6, 7, 8, 9],
    blurb: "Street-food capitals, cool tea highlands, one of the world's oldest rainforests and easy-going islands, all linked by cheap buses and hawker centres.",
    route: "Kuala Lumpur, the Cameron Highlands, Penang, then across to the Perhentians. 2 to 3 weeks.",
    places: [
      { id: "penang", name: "George Town, Penang", d: [11, 8, 3, 4], tags: ["food", "culture", "city"],
        highlight: "Eat char kway teow at hawker stalls, hunt for street art murals and explore clan houses in George Town's colonial-era old town.",
        tip: "Eat at hawker centres like Gurney Drive. The free CAT bus loops the old town." },
      { id: "cameron", name: "Cameron Highlands", d: [11, 8, 3, 4], tags: ["nature", "trekking", "mountains"],
        highlight: "Rolling tea plantations, mossy forest trails and cool mountain air make a welcome break from the lowland heat.",
        tip: "Hike the numbered jungle trails yourself instead of joining a tour, and visit tea estates for free." },
      { id: "perhentian", name: "Perhentian Islands", d: [14, 11, 6, 8], tags: ["beach", "nature"],
        highlight: "Snorkel in clear water with sea turtles and blacktip reef sharks off white sand beaches.",
        tip: "Long Beach on Kecil is the budget side. Islands close in the monsoon, roughly November to February." },
      { id: "taman-negara", name: "Taman Negara", d: [10, 9, 6, 8], tags: ["offbeat", "nature", "trekking"],
        highlight: "Explore one of the world's oldest rainforests on a canopy walkway, jungle treks and overnight stays in wildlife hides.",
        tip: "Stay in Kuala Tahan across the river from the park. Floating restaurants serve cheap meals." }
    ] },
  { id: "taiwan", name: "Taiwan", region: "East Asia", currency: "New Taiwan dollar (TWD)", best: [3, 4, 5, 10, 11],
    blurb: "Night markets, marble gorges and mountain tea villages, all linked by spotless trains, with cheap street food and hostels that make Taiwan easy on a budget.",
    route: "Taipei, the east coast to Taroko, then down to Alishan and Tainan. 2 weeks.",
    places: [
      { id: "taipei", name: "Taipei", d: [18, 12, 4, 5], tags: ["city", "food"],
        highlight: "Graze on stinky tofu and bubble tea at night markets, hike Elephant Mountain for skyline views and soak in Beitou's hot springs.",
        tip: "Get an EasyCard for the metro and buses. Night market dinners run about $5 for several snacks." },
      { id: "taroko", name: "Taroko Gorge", d: [18, 12, 6, 3], tags: ["nature", "trekking", "mountains"],
        highlight: "Sheer marble cliffs, trails cut into the gorge walls and turquoise rivers just outside Hualien on the east coast.",
        tip: "Some trails were closed after the 2024 earthquake. Check which are open before you go, and use local buses from Hualien." },
      { id: "alishan", name: "Alishan", d: [18, 11, 8, 5], tags: ["mountains", "offbeat", "trekking"],
        highlight: "Watch sunrise over a sea of clouds, walk through ancient cypress forests and sip high-mountain oolong on tea farms.",
        tip: "Stay in Fenqihu or a tea-farm homestay for cheaper beds than the hotels in the forest recreation area." }
    ] },
  { id: "mongolia", name: "Mongolia", region: "East Asia", currency: "Mongolian tögrög (MNT)", best: [6, 7, 8, 9],
    blurb: "Endless steppe, nomad gers, horse treks and the Gobi Desert, best seen on a shared multi-day jeep tour that splits the cost of driver, food and fuel.",
    route: "Ulaanbaatar, a week-long jeep trip to the Gobi, then north to Khövsgöl Lake. 3 weeks.",
    places: [
      { id: "ulaanbaatar", name: "Ulaanbaatar", d: [10, 8, 3, 5], tags: ["city", "culture"],
        highlight: "Visit Gandan Monastery, catch a throat singing show and stock up for the overland trips that all start here.",
        tip: "Hostels arrange shared jeep tours. Split one 4 to 6 ways to cut the cost per person." },
      { id: "gobi", name: "Gobi Desert", d: [15, 10, 25, 5], tags: ["offbeat", "nature"],
        highlight: "Climb the singing dunes of Khongoryn Els, see the red Flaming Cliffs at sunset and spend nights in nomad gers.",
        tip: "Tours of 6 to 8 days include driver, food and gers. Bring wet wipes, because showers are rare." },
      { id: "khovsgol", name: "Khövsgöl Lake", d: [14, 9, 15, 5], tags: ["offbeat", "nature", "trekking"],
        highlight: "A huge, clear alpine lake near the Siberian border, with horse treks through larch forests to visit reindeer herders.",
        tip: "Fly or take a long bus to Mörön, then a shared van to Khatgal, the cheapest base for lake trips." },
      { id: "terelj", name: "Terelj National Park", d: [14, 9, 5, 5], tags: ["nature", "trekking"],
        highlight: "Granite rock formations like Turtle Rock, horse riding across meadows and a night in a ger close to the capital.",
        tip: "A public bus runs from Ulaanbaatar. Stay with a nomad family rather than a tourist camp for a cheaper, more genuine experience." }
    ] },
  { id: "uzbekistan", name: "Uzbekistan", region: "Central Asia", currency: "Uzbek som (UZS)", best: [4, 5, 9, 10],
    blurb: "Silk Road cities of blue-tiled domes and madrasas, connected by fast trains and fueled by plov, with family guesthouses and big breakfasts at low prices.",
    route: "Tashkent, the fast train to Samarkand, then Bukhara and Khiva, with Nukus for the Aral Sea. 2 weeks.",
    places: [
      { id: "samarkand", name: "Samarkand", d: [12, 8, 3, 6], tags: ["history", "culture"],
        highlight: "Stand in the Registan square at dusk, walk the avenue of tiled tombs at Shah-i-Zinda and visit the vast Bibi-Khanym mosque.",
        tip: "Book Afrosiyob fast trains early on the railway website, as they sell out days ahead in high season." },
      { id: "bukhara", name: "Bukhara", d: [12, 8, 3, 5], tags: ["history", "culture"],
        highlight: "A walkable old town of madrasas, covered trading domes and the Kalyan minaret, with tea houses around the Lyabi-Hauz pool.",
        tip: "Family guesthouses in the old town include big breakfasts, so you can skip lunch on a budget." },
      { id: "khiva", name: "Khiva", d: [12, 8, 4, 8], tags: ["history", "culture"],
        highlight: "A complete walled city of mud-brick minarets and madrasas that glows golden at sunset from the ramparts.",
        tip: "One ticket covers most sites inside Itchan Kala for 2 days, so you can explore slowly." },
      { id: "moynaq", name: "Nukus & Moynaq", d: [12, 7, 8, 5], tags: ["offbeat", "history"],
        highlight: "See the Savitsky Museum's collection of banned Soviet art, then the rusting ships stranded where the Aral Sea used to be.",
        tip: "Share a taxi to Moynaq from Nukus to cut costs. The Savitsky collection is one of the best in Central Asia." }
    ] },
  { id: "tajikistan", name: "Tajikistan", region: "Central Asia", currency: "Tajik somoni (TJS)", best: [6, 7, 8, 9],
    blurb: "The Pamir Highway, turquoise mountain lakes and homestay hospitality in one of the least-visited countries in Asia, where travel is cheap but rugged.",
    route: "Dushanbe, the Fann Mountains, then the Pamir Highway east toward Kyrgyzstan. 2 to 3 weeks.",
    places: [
      { id: "dushanbe", name: "Dushanbe", d: [12, 7, 3, 3], tags: ["city", "food"],
        highlight: "Wide tree-lined boulevards, the Green Bazaar's piles of dried fruit and the starting point for every mountain trip.",
        tip: "Shared taxis leave from city stands for every direction, and they are much cheaper than private drivers." },
      { id: "pamir", name: "Pamir Highway", d: [14, 8, 20, 5], tags: ["offbeat", "mountains", "nature"],
        highlight: "One of the world's great road trips crosses 4,000 m passes and follows the Wakhan Valley along the Afghan border.",
        tip: "You need a GBAO permit with your e-visa. Share a 4x4 and driver from Khorog with other travelers to split the cost." },
      { id: "fann", name: "Fann Mountains & Iskanderkul", d: [10, 8, 6, 3], tags: ["offbeat", "trekking", "mountains"],
        highlight: "Hike past the Seven Lakes of Marguzor and on multi-day treks to turquoise alpine lakes like Iskanderkul and the Kulikalon basin.",
        tip: "Homestays in the Marguzor villages cost little and include home-cooked meals, so you can trek with a light pack." }
    ] },
  { id: "kazakhstan", name: "Kazakhstan", region: "Central Asia", currency: "Kazakhstani tenge (KZT)", best: [5, 6, 7, 8, 9],
    blurb: "Modern Almaty backed by the snowy Tian Shan, with canyons, alpine lakes and cheap homestays a short drive away.",
    route: "Almaty, then a loop to Charyn Canyon and the Kolsai Lakes. 1 week, easily added to Kyrgyzstan.",
    places: [
      { id: "almaty", name: "Almaty", d: [14, 10, 3, 5], tags: ["city", "mountains"],
        highlight: "Leafy avenues, the Green Bazaar and day hikes from Medeu or up to the turquoise Big Almaty Lake in the mountains.",
        tip: "Use Yandex Go for cheap taxis. Bus 12 runs from the center to the mountains at Medeu." },
      { id: "charyn", name: "Charyn Canyon", d: [15, 9, 12, 4], tags: ["nature", "offbeat"],
        highlight: "Walk through the Valley of Castles, a red rock canyon often compared to a mini Grand Canyon, down to the Charyn river.",
        tip: "Combine it with Kolsai Lakes on a 2 or 3 day shared tour from Almaty to split transport costs." },
      { id: "kolsai", name: "Kolsai & Kaindy Lakes", d: [14, 9, 8, 4], tags: ["nature", "trekking", "offbeat"],
        highlight: "Hike between spruce-ringed alpine lakes and see Kaindy's sunken forest, where drowned tree trunks poke out of the water.",
        tip: "Homestays in Saty village are the cheapest base, and most hosts include home-cooked meals." }
    ] },
  { id: "pakistan", name: "Pakistan", region: "South Asia", currency: "Pakistani rupee (PKR)", best: [5, 6, 7, 8, 9, 10],
    advisory: "Many governments advise against travel to parts of Pakistan, including Balochistan, much of Khyber Pakhtunkhwa and areas near the Afghan and Indian borders, because of terrorism. The Karakoram Highway passes through some of these areas, so check current advice for your route.",
    blurb: "Some of the world's highest mountains and most generous hospitality, still far off the main trail. Several regions carry travel warnings, so check current advice for your route.",
    route: "Islamabad, the Karakoram Highway to Hunza, then Skardu and Fairy Meadows. 3 weeks.",
    places: [
      { id: "lahore", name: "Lahore", d: [10, 5, 3, 3], tags: ["city", "food", "history"],
        highlight: "Mughal forts and mosques, food street feasts of karahi and naan, and the flag-lowering ceremony at the Wagah border.",
        tip: "Walk the old city with a local guide. Visit outside the hottest months, roughly May to August." },
      { id: "hunza", name: "Hunza Valley", d: [10, 7, 5, 4], tags: ["offbeat", "mountains", "trekking"],
        highlight: "Apricot orchards below 7,000 m peaks, the ancient Baltit Fort and the jagged Passu Cones along the Karakoram Highway.",
        tip: "Shared vans run up the Karakoram Highway from Gilgit. Check travel advice and register where asked." },
      { id: "fairy-meadows", name: "Fairy Meadows", d: [12, 8, 12, 5], tags: ["offbeat", "trekking", "mountains"],
        highlight: "Alpine meadows facing the vast north face of Nanga Parbat, known as the 'killer mountain', with camping under the peak.",
        tip: "A jeep ride and a 3 hour hike get you there. Basic huts and camping are available." },
      { id: "skardu", name: "Skardu", d: [11, 7, 6, 4], tags: ["offbeat", "nature", "mountains"],
        highlight: "Cold deserts, Shangrila Lake and the gateway to the K2 base camp trek, surrounded by some of Earth's biggest peaks.",
        tip: "Flights from Islamabad are often cancelled for weather. Leave buffer days in your plan." }
    ] },
  { id: "armenia", name: "Armenia", region: "Europe & Caucasus", currency: "Armenian dram (AMD)", best: [5, 6, 9, 10],
    blurb: "Ancient monasteries on cliff edges, wine caves and a café-filled capital with views of Mount Ararat, all at low prices and with very few crowds.",
    route: "Yerevan, north to Dilijan, then south through Areni to Tatev. 10 days, easy to pair with Georgia.",
    places: [
      { id: "yerevan", name: "Yerevan", d: [12, 9, 2, 4], tags: ["city", "food", "culture"],
        highlight: "Climb the Cascade for views of Mount Ararat, browse the Vernissage flea market and sip coffee in the pink-stone city's cafés.",
        tip: "Marshrutkas and the metro cost cents. Day trip to Garni temple and Geghard monastery by shared taxi." },
      { id: "dilijan", name: "Dilijan", d: [12, 9, 3, 2], tags: ["nature", "trekking"],
        highlight: "Forested mountains, the stone monastery of Haghartsin and day hikes on sections of the Transcaucasian Trail.",
        tip: "Family guesthouses serve home-cooked dinners with local cheese, herbs and fruit, often cheaper than eating out in town." },
      { id: "tatev", name: "Tatev Monastery", d: [13, 9, 6, 8], tags: ["history", "mountains", "offbeat"],
        highlight: "A 9th-century monastery on the edge of a gorge, reached by one of the world's longest cable cars.",
        tip: "Hike down to the Devil's Bridge hot springs in the gorge below for a free swim." },
      { id: "areni", name: "Areni", d: [12, 9, 4, 4], tags: ["food", "offbeat", "history"],
        highlight: "Taste wine at village wineries and visit the cave where the world's oldest known winery was found.",
        tip: "Visit in early October for the Areni wine festival, with tastings and folk music in the village." }
    ] },
  { id: "bosnia", name: "Bosnia and Herzegovina", region: "Europe & Caucasus", currency: "Convertible mark (BAM)", best: [5, 6, 7, 8, 9],
    blurb: "Ottoman bazaars, emerald rivers and mountain villages at some of Europe's lowest prices, with ćevapi, strong coffee and welcoming guesthouses.",
    route: "Sarajevo, the train to Mostar, with Blagaj, Kravica and the mountain village of Lukomir. 10 days.",
    places: [
      { id: "sarajevo", name: "Sarajevo", d: [14, 11, 3, 5], tags: ["city", "history", "food"],
        highlight: "Wander Baščaršija's copper-workers' bazaar, eat ćevapi, walk through the Tunnel of Hope and watch sunset from the Yellow Bastion.",
        tip: "Ćevapi with somun bread is a full meal for about $5. Free walking tours explain the city's history." },
      { id: "mostar", name: "Mostar", d: [15, 12, 4, 4], tags: ["history", "culture"],
        highlight: "Watch divers leap from the Old Bridge, then take day trips to Kravica falls and the dervish house at Blagaj.",
        tip: "The Sarajevo to Mostar train is one of Europe's most scenic rides, and it is cheap." },
      { id: "lukomir", name: "Lukomir", d: [19, 10, 11, 2], tags: ["offbeat", "trekking", "mountains"],
        highlight: "Bosnia's highest and most remote village, with stone houses perched on a canyon rim and shepherds grazing flocks in summer.",
        tip: "Reachable only by dirt road or hiking. Go with a guide from Sarajevo or stay in the village guesthouse." }
    ] },
  { id: "montenegro", name: "Montenegro", region: "Europe & Caucasus", currency: "Euro (EUR)", best: [5, 6, 9, 10],
    blurb: "A fjord-like bay, wild mountain canyons and Balkan prices just inland from the coast, with cheap private rooms, campsites and hearty mountain food.",
    route: "Kotor, inland to Žabljak and Durmitor, then down to Lake Skadar. 10 days.",
    places: [
      { id: "kotor", name: "Kotor", d: [24, 17, 5, 5], tags: ["history", "trekking", "beach"],
        highlight: "Get lost in a walled medieval old town, then climb the switchback path to the fortress high above the Bay of Kotor.",
        tip: "Climb the fortress before 8 a.m. to skip the fee and the heat. Stay outside the walls for cheaper rooms." },
      { id: "durmitor", name: "Žabljak & Durmitor", d: [18, 14, 6, 3], tags: ["mountains", "trekking", "nature"],
        highlight: "Swim in Black Lake, cross the Tara Canyon bridge and hike to the summit of Bobotov Kuk in Durmitor National Park.",
        tip: "Camping and private rooms are cheap in Žabljak. Rafting the Tara is best in late spring." },
      { id: "skadar", name: "Lake Skadar", d: [18, 13, 6, 5], tags: ["offbeat", "nature"],
        highlight: "Glide past water lilies, pelicans and sleepy fishing villages on the Balkans' largest lake, surrounded by vineyards.",
        tip: "Stay in Virpazar or Rijeka Crnojevića and hire a local boatman instead of booking a tour from the coast." }
    ] },
  { id: "north-macedonia", name: "North Macedonia", region: "Europe & Caucasus", currency: "Macedonian denar (MKD)", best: [5, 6, 7, 8, 9],
    blurb: "A lake older than most on Earth, Ottoman bazaars, mountain villages and almost no crowds, with cheap burek and private rooms.",
    route: "Skopje, Matka Canyon, then west via Mavrovo to Lake Ohrid. 1 week.",
    places: [
      { id: "skopje", name: "Skopje", d: [13, 10, 3, 3], tags: ["city", "history"],
        highlight: "An eccentric center packed with giant statues, the Old Bazaar's mosques and teahouses, and kayaking in nearby Matka Canyon.",
        tip: "Burek and yogurt make a cheap breakfast. Bus 60 goes to Matka Canyon, an easy day trip from Skopje." },
      { id: "ohrid", name: "Ohrid", d: [14, 11, 4, 3], tags: ["history", "beach", "culture"],
        highlight: "Byzantine churches cling to cliffs above a clear lake, with lazy beach days and swims along its shore.",
        tip: "Rent a room from locals at the bus station. Swim at Gradište or Ljubaništa for quieter beaches." },
      { id: "mavrovo", name: "Mavrovo", d: [15, 11, 5, 2], tags: ["offbeat", "nature", "trekking"],
        highlight: "A half-submerged church in a reservoir, the stone village of Galičnik and walks toward Korab, the country's highest peak.",
        tip: "Visit Galičnik in July for its traditional wedding festival, with folk dress, music and dancing." }
    ] },
  { id: "romania", name: "Romania", region: "Europe & Caucasus", currency: "Romanian leu (RON)", best: [5, 6, 7, 8, 9],
    blurb: "Medieval Saxon towns, Carpathian hikes, painted wooden churches and villages where time seems to have stopped, all at low prices.",
    route: "Bucharest, Brașov and Bran, Sibiu, then north to Maramureș. 2 weeks.",
    places: [
      { id: "brasov", name: "Brașov", d: [16, 13, 3, 5], tags: ["history", "mountains"],
        highlight: "Stroll a medieval old town under the Tâmpa hillside, day trip to Bran castle and hike the ridges of Piatra Craiului.",
        tip: "Local buses run to Bran and Râșnov. Eat at a cantina, a simple canteen, for a cheap lunch." },
      { id: "sibiu", name: "Sibiu", d: [16, 13, 3, 4], tags: ["history", "culture"],
        highlight: "A Saxon town where roof windows look down like 'eyes', with fortified Saxon churches in villages nearby.",
        tip: "Drive or tour the Transfăgărășan road, which is usually open July to October, and share the car hire." },
      { id: "maramures", name: "Maramureș", d: [16, 12, 5, 3], tags: ["offbeat", "culture"],
        highlight: "Tall wooden churches, the colorful Merry Cemetery and village life still moving at the pace of horse carts.",
        tip: "Stay in a farm guesthouse that serves home-made food. The Mocănița steam train runs in summer." },
      { id: "danube-delta", name: "Danube Delta", d: [17, 13, 8, 6], tags: ["offbeat", "nature"],
        highlight: "Paddle through reed-lined channels full of pelicans and herons in Europe's largest wetland, staying in quiet fishing villages.",
        tip: "Take the public ferry from Tulcea to Sulina and hire a local fisherman's boat for cheaper trips." }
    ] },
  { id: "bulgaria", name: "Bulgaria", region: "Europe & Caucasus", currency: "Euro (EUR)", best: [5, 6, 7, 8, 9],
    blurb: "Roman ruins, painted monasteries, mountain lakes and some of the EU's cheapest food, from banitsa breakfasts to shopska salad.",
    route: "Sofia, Rila, Plovdiv and Veliko Tarnovo. 10 days.",
    places: [
      { id: "sofia", name: "Sofia", d: [14, 12, 2, 3], tags: ["city", "history"],
        highlight: "Gold-domed Alexander Nevsky Cathedral, Roman ruins in the metro stations and hiking on Vitosha mountain just above the city.",
        tip: "Free walking tours run twice a day. Banitsa pastries are breakfast for cents at local bakeries." },
      { id: "rila", name: "Rila Monastery & Seven Lakes", d: [16, 12, 6, 3], tags: ["trekking", "mountains", "history"],
        highlight: "Visit the painted Rila Monastery in the mountains, then walk the ridge above the glacial Seven Rila Lakes.",
        tip: "Go on a weekday to avoid the crowds. Mountain huts offer cheap bunks and simple meals." },
      { id: "plovdiv", name: "Plovdiv", d: [14, 12, 2, 3], tags: ["history", "culture"],
        highlight: "A Roman theatre still used for summer concerts, a hilly old town and the creative bars of the Kapana district.",
        tip: "The old town's colorful houses are best seen on foot at sunset, and walking is free." },
      { id: "veliko-tarnovo", name: "Veliko Tarnovo", d: [13, 11, 2, 4], tags: ["history"],
        highlight: "Tsarevets fortress towers above a river gorge, with the old merchant village of Arbanasi a short walk away.",
        tip: "Stay a night to see the fortress sound and light show, which you can watch for free from the streets." }
    ] },
  { id: "turkey", name: "Turkey", region: "Europe & Caucasus", currency: "Turkish lira (TRY)", best: [4, 5, 6, 9, 10],
    blurb: "Bazaars and ferries in Istanbul, Cappadocia's fairy chimneys, a turquoise coast and Mesopotamian towns, with cheap street food and pensions throughout.",
    route: "Istanbul, night bus to Cappadocia, down to Kaş, then east to Mardin. 3 weeks.",
    places: [
      { id: "istanbul", name: "Istanbul", d: [20, 14, 5, 15], tags: ["city", "food", "history"],
        highlight: "Stand under the dome of Hagia Sophia, haggle in the Grand Bazaar and take the cheapest Bosphorus cruise there is: the public ferry.",
        tip: "Get an Istanbulkart for trams and ferries. Balık ekmek, a grilled fish sandwich by the Galata Bridge, is a cheap lunch." },
      { id: "cappadocia", name: "Cappadocia", d: [18, 13, 6, 10], tags: ["nature", "trekking", "history"],
        highlight: "Fairy chimneys, cave hotels and valley hikes at dawn, with hundreds of hot-air balloons floating overhead.",
        tip: "Watch the balloons from the ground for free. Hike the Rose and Love valleys without a tour." },
      { id: "kas", name: "Kaş", d: [19, 14, 5, 6], tags: ["beach", "trekking"],
        highlight: "Turquoise coves, hikes along the Lycian Way and kayaking over the sunken ruins at Kekova.",
        tip: "Walk sections of the Lycian Way and camp or stay in family-run village pensions along the route." },
      { id: "mardin", name: "Mardin", d: [16, 12, 5, 3], tags: ["offbeat", "history", "culture"],
        highlight: "Honey-colored stone houses step down a hill toward the Mesopotamian plain, with ancient Syriac monasteries nearby.",
        tip: "Pair it with Şanlıurfa and Göbekli Tepe, the world's oldest known temple, by cheap intercity bus." }
    ] },
  { id: "ecuador", name: "Ecuador", region: "Latin America", currency: "US dollar (USD)", best: [6, 7, 8, 9, 12, 1],
    blurb: "Volcanoes, cloud forest, Andean markets and the Amazon in a country you can cross in a day, with cheap buses and set lunches everywhere.",
    route: "Quito, Mindo, the Quilotoa Loop, Baños, then Cuenca. 2 to 3 weeks.",
    places: [
      { id: "quito", name: "Quito", d: [12, 9, 2, 5], tags: ["city", "history", "mountains"],
        highlight: "Wander a UNESCO-listed colonial center, ride the TelefériQo up Pichincha volcano and straddle the equator line just outside town.",
        tip: "City buses cost cents. Use taxis or ride apps at night rather than walking." },
      { id: "quilotoa", name: "Quilotoa Loop", d: [15, 7, 4, 3], tags: ["offbeat", "trekking", "mountains"],
        highlight: "A 3 or 4 day village-to-village hike through Andean farmland, ending at the rim of a turquoise crater lake.",
        tip: "Hostels along the loop include dinner and breakfast. Leave big bags in Latacunga and hike light." },
      { id: "banos", name: "Baños", d: [11, 9, 3, 6], tags: ["nature", "trekking"],
        highlight: "Chase waterfalls, ride the 'swing at the end of the world' and cycle down the Ruta de las Cascadas to the Pailón del Diablo.",
        tip: "Rent a bike and take the bus back up. The thermal hot springs open at 5 a.m., before the crowds." },
      { id: "cuenca", name: "Cuenca", d: [12, 8, 2, 4], tags: ["history", "culture"],
        highlight: "Blue-domed cathedrals, riverside walks and day hikes among the lakes of El Cajas national park.",
        tip: "Market lunches are about $3. Cajas is free and a short bus ride from Cuenca." },
      { id: "mindo", name: "Mindo", d: [12, 9, 3, 5], tags: ["nature", "offbeat"],
        highlight: "Cloud forest full of hummingbirds and butterflies, with waterfall hikes and bean-to-bar chocolate farm tours.",
        tip: "Many waterfall trails charge only a few dollars entry. Hostels often have hummingbird feeders in the garden." }
    ] },
  { id: "nicaragua", name: "Nicaragua", region: "Latin America", currency: "Nicaraguan córdoba (NIO)", best: [12, 1, 2, 3, 4],
    blurb: "Colonial cities, volcano adventures, a lake island and Caribbean beaches at Central America's lowest prices, with cheap hostels and street food.",
    route: "León, Granada, Ometepe, then fly to the Corn Islands. 2 to 3 weeks.",
    places: [
      { id: "leon", name: "León", d: [10, 8, 3, 6], tags: ["culture", "history"],
        highlight: "Sled down the black slopes of Cerro Negro on a volcano boarding trip, then walk on the white roof of the cathedral.",
        tip: "Book volcano boarding through a hostel. Fritanga street stalls serve cheap grilled dinners." },
      { id: "granada", name: "Granada", d: [10, 8, 3, 5], tags: ["history", "culture"],
        highlight: "A colorful colonial town, kayaking among the isletas of Lake Nicaragua and a night look at Masaya volcano's glowing lava.",
        tip: "Chicken buses to Masaya cost under $1 and leave regularly from near the market." },
      { id: "ometepe", name: "Ometepe", d: [10, 8, 5, 5], tags: ["nature", "trekking"],
        highlight: "Twin volcanoes rise out of Lake Nicaragua on this island of beaches, farm stays and jungle waterfalls.",
        tip: "Rent a scooter to get around. Climbing Concepción takes a full day and a guide." },
      { id: "little-corn", name: "Little Corn Island", d: [15, 11, 10, 6], tags: ["offbeat", "beach"],
        highlight: "No cars, just reefs, palm-lined beaches and jungle paths on a tiny island off the Caribbean coast.",
        tip: "Fly to Big Corn, then take the panga boat across. Bring cash, since ATMs are limited." }
    ] },
  { id: "honduras", name: "Honduras", region: "Latin America", currency: "Honduran lempira (HNL)", best: [2, 3, 4, 5, 8],
    blurb: "Cheap Caribbean diving and Mayan ruins, best kept to the well-traveled route between Copán and the Bay Islands. Check current travel advice before going.",
    route: "Copán Ruinas from Guatemala, then across to Utila. 10 days.",
    places: [
      { id: "utila", name: "Utila", d: [12, 10, 2, 25], tags: ["beach", "nature"],
        highlight: "One of the cheapest places in the world to learn to dive, with coral reefs and whale sharks in season.",
        tip: "Dive shops often include free dorm nights with a course, so compare packages before signing up." },
      { id: "copan", name: "Copán Ruinas", d: [12, 8, 3, 10], tags: ["history", "offbeat"],
        highlight: "Intricately carved Mayan stelae, a hieroglyphic stairway and a macaw sanctuary next to a cobbled colonial town.",
        tip: "An easy shuttle ride from Antigua, Guatemala. Check current travel advice for elsewhere in the country." }
    ] }
];

// More places in the countries above, mostly lesser-known spots off the main tourist trail.
const MORE_PLACES = {
  vietnam: [
    { id: "phong-nha", name: "Phong Nha", d: [8, 8, 4, 10], tags: ["nature", "trekking", "offbeat"],
      highlight: "Home to some of the world's biggest caves, where Paradise Cave and Phong Nha Cave can be visited without a tour.",
      tip: "Rent a bicycle to ride the valley loop past rice paddies. Multi-day cave expeditions cost far more and book out early, so plan ahead." },
    { id: "cao-bang", name: "Cao Bằng & Ban Gioc", d: [8, 8, 8, 4], tags: ["offbeat", "nature", "mountains"],
      highlight: "Ban Gioc waterfall thunders across the Chinese border, surrounded by quiet karst valleys and rice fields that see very few tourists.",
      tip: "Combine it with the Ha Giang Loop by motorbike, or take a cheap overnight sleeper bus from Hanoi to save a night's accommodation." }
  ],
  laos: [
    { id: "thakhek", name: "Thakhek Loop", d: [8, 8, 8, 4], tags: ["offbeat", "nature"],
      highlight: "A 3 or 4 day motorbike loop through karst country that ends at Kong Lor, a river cave stretching 7 km underground.",
      tip: "Rent bikes in Thakhek town. Boat trips through Kong Lor are priced per boat, so share one with other travelers to cut the cost." },
    { id: "si-phan-don", name: "4,000 Islands", d: [8, 8, 4, 4], tags: ["nature", "beach"],
      highlight: "Swing in a hammock on Don Det or Don Khon, look for rare river dolphins and feel the spray at Khone Phapheng falls.",
      tip: "Bikes cost about $1 a day to explore the islands. Don Khon is quieter than Don Det if you want calm nights." }
  ],
  thailand: [
    { id: "khao-sok", name: "Khao Sok", d: [12, 10, 5, 10], tags: ["nature", "trekking"],
      highlight: "Trek through ancient rainforest, then sleep in floating bungalows on Cheow Lan lake, surrounded by jungle and limestone cliffs.",
      tip: "Book overnight lake trips in the village, where you can compare prices between operators face to face instead of paying online markups." },
    { id: "koh-phayam", name: "Koh Phayam", d: [13, 11, 5, 3], tags: ["offbeat", "beach"],
      highlight: "No cars, quiet beaches and simple wooden bungalows make this small island near the Myanmar border a cheap, slow escape.",
      tip: "Ferries leave from Ranong on the mainland. Bring cash with you, as there are few ATMs on the island." }
  ],
  cambodia: [
    { id: "koh-rong-samloem", name: "Koh Rong Samloem", d: [10, 9, 6, 4], tags: ["beach"],
      highlight: "White sand bays, clear water and glowing bioluminescent plankton on night swims, with simple beach bungalows instead of resorts.",
      tip: "Ferries leave from Sihanoukville. Stay on Lazy Beach or Saracen Bay for the calmest water and easy swimming." },
    { id: "ratanakiri", name: "Banlung & Ratanakiri", d: [8, 7, 6, 6], tags: ["offbeat", "nature"],
      highlight: "Red dirt roads lead to a volcanic crater lake and jungle treks in Cambodia's remote northeast, where few tourists venture.",
      tip: "Swim in Yeak Laom crater lake for a small fee. Arrange jungle treks with guesthouses in Banlung to keep costs down." }
  ],
  indonesia: [
    { id: "toraja", name: "Tana Toraja", d: [10, 7, 5, 6], tags: ["offbeat", "culture"],
      highlight: "Boat-shaped tongkonan houses, cliff graves and elaborate funeral ceremonies make this Sulawesi highland culture unlike anywhere else in Indonesia.",
      tip: "Hire a local guide in Rantepao to attend a funeral respectfully. Overnight buses run from Makassar and save a night's accommodation." },
    { id: "ijen", name: "Kawah Ijen", d: [10, 6, 8, 10], tags: ["offbeat", "trekking", "nature"],
      highlight: "Hike through the night to see blue sulfur flames glowing in the crater, then watch dawn reveal an acid-turquoise lake in East Java.",
      tip: "Stay in cheap guesthouses in Banyuwangi. Bring a proper gas mask for the crater, since the fumes can be strong." },
    { id: "gili-air", name: "Gili Air", d: [12, 10, 4, 5], tags: ["beach"],
      highlight: "No cars, just bicycles and horse carts, with sea turtles grazing on seagrass a short swim off the beach.",
      tip: "It's quieter and cheaper than Gili Trawangan. Snorkel gear rental is a couple of dollars, so skip the boat tours." }
  ],
  nepal: [
    { id: "bandipur", name: "Bandipur", d: [9, 8, 4, 2], tags: ["offbeat", "culture", "mountains"],
      highlight: "A car-free Newari hill town of old brick houses with wide Himalayan views, halfway between Kathmandu and Pokhara.",
      tip: "Get off the Kathmandu to Pokhara bus at Dumre and take a cheap local jeep up the hill." },
    { id: "chitwan", name: "Chitwan National Park", d: [8, 9, 4, 15], tags: ["nature"],
      highlight: "Go on jungle walks and dugout canoe trips past one-horned rhinos, crocodiles and, with luck, tracks of Bengal tigers.",
      tip: "Stay in Sauraha's budget guesthouses and book jungle walks directly with licensed guides instead of through Kathmandu agencies." }
  ],
  india: [
    { id: "hampi", name: "Hampi", d: [7, 5, 3, 4], tags: ["history", "nature"],
      highlight: "Vijayanagara temple ruins lie scattered among giant golden boulders and banana fields, best seen from a hilltop at sunset.",
      tip: "Cross the river to Hampi Island for cheap guesthouses. Rent a bicycle or scooter to reach the outlying temples." },
    { id: "spiti", name: "Spiti Valley", d: [9, 7, 8, 3], tags: ["offbeat", "mountains"],
      highlight: "A Himalayan cold desert of high villages and ancient cliffside monasteries like Key and Dhankar, under huge open skies.",
      tip: "Roads are only reliably open in summer. Shared taxis and buses run from Manali or Shimla, and they are much cheaper than a private driver." },
    { id: "meghalaya", name: "Meghalaya", d: [9, 6, 5, 3], tags: ["offbeat", "trekking", "nature"],
      highlight: "Hike down to the double-decker living root bridge at Nongriat, then float on the glass-clear river at Dawki.",
      tip: "Stay in a Nongriat homestay rather than day-tripping. Expect thousands of steps each way, so pack light." }
  ],
  "sri-lanka": [
    { id: "arugam-bay", name: "Arugam Bay", d: [12, 10, 4, 6], tags: ["beach"],
      highlight: "A relaxed surf town on the east coast with point breaks, beach shacks and lagoon safaris, best from May to September.",
      tip: "Surf lessons and board hire are cheap. Visit in the east coast season, which is the opposite of the south coast's." },
    { id: "knuckles", name: "Knuckles Range", d: [12, 9, 5, 8], tags: ["offbeat", "trekking", "mountains"],
      highlight: "Trek through cloud forest and tea villages in a misty mountain range, sleeping in homestays far from the tourist crowds.",
      tip: "A guide is required for most trails. Base yourself in Kandy or a village homestay with home-cooked meals." }
  ],
  kyrgyzstan: [
    { id: "arslanbob", name: "Arslanbob", d: [9, 7, 4, 3], tags: ["offbeat", "nature", "trekking"],
      highlight: "Hike through the world's largest walnut forest to waterfalls, staying with Uzbek families through a community tourism homestay network.",
      tip: "The local CBT office arranges affordable homestays and horse treks, and your money stays in the village." }
  ],
  georgia: [
    { id: "tusheti", name: "Tusheti", d: [15, 10, 15, 3], tags: ["offbeat", "mountains", "trekking"],
      highlight: "Medieval tower villages and wild mountain trails at the end of one of the world's most dangerous roads.",
      tip: "The road is only open roughly June to October. Share a 4x4 from Alvani to split the fare." },
    { id: "vardzia", name: "Vardzia", d: [12, 9, 6, 4], tags: ["offbeat", "history"],
      highlight: "A 12th-century cave monastery carved into a cliff face in southern Georgia, with tunnels, chapels and frescoes to explore.",
      tip: "Stay in cheaper Akhaltsikhe and combine the trip with a visit to Rabati castle." }
  ],
  albania: [
    { id: "gjirokaster", name: "Gjirokastër", d: [14, 12, 4, 3], tags: ["history", "culture"],
      highlight: "A stone 'city of a thousand steps' with slate-roofed Ottoman houses and a hilltop castle overlooking the Drino valley.",
      tip: "Try qifqi, the local rice balls, at family restaurants. Day trip to the Blue Eye spring by local bus." },
    { id: "permet", name: "Përmet", d: [14, 12, 5, 3], tags: ["offbeat", "nature"],
      highlight: "Soak in the Benja thermal springs under an Ottoman bridge, then raft the wild Vjosa river through its canyons.",
      tip: "Taste the local raki and fruit preserves the town is known for, sold cheaply in small shops." }
  ],
  poland: [
    { id: "bialowieza", name: "Białowieża Forest", d: [20, 14, 10, 6], tags: ["offbeat", "nature"],
      highlight: "Europe's last primeval lowland forest, where herds of wild European bison roam among ancient oaks on the Belarus border.",
      tip: "Rent a bike in Białowieża village to ride the forest trails. The strict reserve needs a guide." }
  ],
  morocco: [
    { id: "essaouira", name: "Essaouira", d: [13, 10, 4, 3], tags: ["beach", "culture"],
      highlight: "A windswept Atlantic port with blue fishing boats, a relaxed medina and grilled sardines straight from the harbor.",
      tip: "Buy fish at the port and have it grilled at the stalls for a few dollars, cheaper than any restaurant." },
    { id: "todra", name: "Todra Gorge", d: [11, 9, 6, 3], tags: ["trekking", "nature", "offbeat"],
      highlight: "Hike between 300-metre canyon walls, try rock climbing and visit Berber villages near the Dadès valley.",
      tip: "Guesthouses in the gorge include dinner. Walk the loop over to the nomad plateau for free views." },
    { id: "tafraoute", name: "Tafraoute", d: [11, 9, 6, 2], tags: ["offbeat", "trekking", "nature"],
      highlight: "Pink granite boulders, almond blossom in February and the palm-filled Ait Mansour gorge in the Anti-Atlas mountains.",
      tip: "Rent a bike to see the famous painted rocks. Few tourists make it this far south, so guesthouses stay cheap." }
  ],
  peru: [
    { id: "huaraz", name: "Huaraz & the Santa Cruz Trek", d: [11, 10, 4, 8], tags: ["trekking", "mountains"],
      highlight: "Day hike to glacier lakes like Laguna 69, or tackle the 4-day Santa Cruz trek through the Cordillera Blanca.",
      tip: "Santa Cruz can be done without a tour if you're experienced. Acclimatise for 2 or 3 days first in Huaraz." },
    { id: "choquequirao", name: "Choquequirao", d: [13, 11, 5, 8], tags: ["offbeat", "trekking", "history"],
      highlight: "Called Machu Picchu's 'sister', these vast Inca ruins are reached only by a tough 4-day hike, so few visitors make it.",
      tip: "Start in Cachora. Hire a mule to carry your bags on the steep canyon climbs, which is cheap and spares your knees." }
  ],
  bolivia: [
    { id: "rurrenabaque", name: "Rurrenabaque", d: [9, 8, 6, 20], tags: ["nature", "offbeat"],
      highlight: "Take pampas river trips to see pink dolphins and caimans, or head into the Amazon rainforest of Madidi National Park.",
      tip: "Choose operators with good animal-welfare reviews. Flights save a rough 20-hour bus ride from La Paz." },
    { id: "samaipata", name: "Samaipata", d: [10, 8, 3, 5], tags: ["offbeat", "nature", "history"],
      highlight: "A pre-Inca carved rock site, giant tree ferns in Amboró National Park and condor viewpoints around a sleepy valley town.",
      tip: "Shared taxis run from Santa Cruz. It's a good place to slow down, with cheap hostels and cafes." }
  ],
  guatemala: [
    { id: "semuc", name: "Semuc Champey", d: [11, 9, 8, 6], tags: ["nature", "offbeat"],
      highlight: "Swim in stepped turquoise pools over a natural limestone bridge, then tube and wade through caves by candlelight.",
      tip: "Stay in Lanquín or near the park in jungle lodges. The shuttle road is rough, so travel light." },
    { id: "xela", name: "Quetzaltenango (Xela)", d: [10, 8, 4, 4], tags: ["culture", "trekking"],
      highlight: "Cheap Spanish schools, hot springs nearby and the 3-day hike from Xela down to Lake Atitlán through highland villages.",
      tip: "Hike with a nonprofit like Quetzaltrekkers, which funds local schools and keeps prices fair." }
  ],
  mexico: [
    { id: "bacalar", name: "Bacalar", d: [17, 13, 5, 5], tags: ["nature", "beach"],
      highlight: "Paddleboard across the 'lagoon of seven colours' and swim in cenotes, a calmer, cheaper alternative to the Caribbean coast.",
      tip: "It's cheaper than Tulum. Swim at the public balnearios for a small fee instead of paying for a boat tour." },
    { id: "real-de-catorce", name: "Real de Catorce", d: [16, 12, 8, 3], tags: ["offbeat", "history"],
      highlight: "Reach this half-abandoned silver-mining town in the desert through a 2 km tunnel, then explore cobbled streets and ghost-town ruins.",
      tip: "Take a Willys jeep or horse ride to the ghost-town ruins, and stay in simple family-run guesthouses." },
    { id: "copper-canyon", name: "Copper Canyon", d: [16, 12, 19, 5], tags: ["offbeat", "trekking", "nature"],
      highlight: "A canyon system bigger than the Grand Canyon, best seen from the windows of the El Chepe train or on hikes from the rim.",
      tip: "Ride El Chepe Regional, not Express, to save money. Stay in Creel or Divisadero for cheap lodges." }
  ],
  colombia: [
    { id: "minca", name: "Minca", d: [12, 10, 4, 4], tags: ["nature", "offbeat"],
      highlight: "Hammock hostels above the clouds, coffee farms and jungle waterfalls in the Sierra Nevada foothills near Santa Marta.",
      tip: "Moto-taxis run from Santa Marta for a cheap ride up. Bring cash, as there are no reliable ATMs." },
    { id: "barichara", name: "Barichara", d: [14, 11, 4, 3], tags: ["offbeat", "history", "trekking"],
      highlight: "A whitewashed colonial village of stone streets and the old Camino Real trail that winds down through canyon country to Guane.",
      tip: "Base yourself in San Gil for cheaper beds and adventure sports like rafting and paragliding." },
    { id: "tatacoa", name: "Tatacoa Desert", d: [13, 10, 8, 4], tags: ["offbeat", "nature"],
      highlight: "Red and grey eroded badlands by day and one of the best stargazing spots in Colombia by night.",
      tip: "Stay out in the desert in a simple hostel to see the stars. The observatory runs night talks." }
  ],
  argentina: [
    { id: "humahuaca", name: "Quebrada de Humahuaca", d: [16, 15, 6, 3], tags: ["offbeat", "mountains", "culture"],
      highlight: "See the Hill of Seven Colours at Purmamarca and the striped peaks of the 14-coloured Hornocal range in the far north.",
      tip: "Use local buses between Purmamarca, Tilcara and Humahuaca, and stay in cheap hostels in Tilcara." },
    { id: "bariloche", name: "Bariloche", d: [22, 19, 6, 5], tags: ["mountains", "trekking", "nature"],
      highlight: "Blue lakes, refugio-to-refugio hikes through Nahuel Huapi National Park and some of Patagonia's best chocolate shops.",
      tip: "Refugios offer cheap bunks on the trail; bring your own sleeping bag and some food to save money." }
  ]
};
window.COUNTRIES.forEach(c => { if (MORE_PLACES[c.id]) c.places.push(...MORE_PLACES[c.id]); });

// Region overrides for the countries above, so every continent has clear groupings.
const REGION_OF = {
  mexico: "North America", guatemala: "Central America & Caribbean", honduras: "Central America & Caribbean",
  nicaragua: "Central America & Caribbean", egypt: "North Africa", morocco: "North Africa", tunisia: "North Africa",
  jordan: "Middle East", turkey: "Middle East", ethiopia: "Sub-Saharan Africa", madagascar: "Sub-Saharan Africa",
  malawi: "Sub-Saharan Africa", georgia: "Caucasus", armenia: "Caucasus"
};
window.COUNTRIES.forEach(c => {
  if (REGION_OF[c.id]) c.region = REGION_OF[c.id];
  else if (c.region === "Latin America") c.region = "South America";
  else if (c.region === "Europe & Caucasus") c.region = "Europe";
});

// More countries live in js/world/*.js. Their places can be compact arrays:
// [id, name, [bed, food, transport, extras], "tag tag", highlight, tip].
// More places for countries that already exist, keyed by country id (js/places/*.js).
// A compact array whose id matches an existing place in that country replaces it.
window.addPlaces = map => Object.entries(map).forEach(([cid, list]) => {
  const c = window.COUNTRIES.find(x => x.id === cid);
  if (!c) { console.warn("addPlaces: unknown country", cid); return; }
  list.forEach(p => {
    const place = { id: p[0], name: p[1], d: p[2], tags: p[3].split(" "), highlight: p[4], tip: p[5], w: p[6] };
    const i = c.places.findIndex(x => x.id === place.id);
    if (i >= 0) c.places[i] = place; else c.places.push(place);
  });
});

window.addCountries = list => list.forEach(c => {
  c.places = c.places.map(p => Array.isArray(p)
    ? { id: p[0], name: p[1], d: p[2], tags: p[3].split(" "), highlight: p[4], tip: p[5], w: p[6] }
    : p);
  window.COUNTRIES.push(c);
});

// Flat list of every place, with its country's details attached. Built once all data files have loaded.
window.buildDestinations = () => window.COUNTRIES.flatMap(c => c.places.map(p => ({
  id: p.id, name: p.name, country: c.name, countryId: c.id, region: c.region,
  daily: { bed: p.d[0], food: p.d[1], transport: p.d[2], extras: p.d[3] },
  best: p.best || c.best, tags: p.tags, highlight: p.highlight, tip: p.tip
})));

