// The town to search for stays and transport at places that are not towns themselves
// (treks, loops, national parks). Used by js/affiliates.js; ids missing here search the place name.
window.PLACE_HUBS = {
"abuko": "Serrekunda",
"acatenango": "Antigua Guatemala",
"adams-peak": "Hatton",
"aggtelek": "Aggtelek",
"akagera": "Kigali",
"akanda": "Libreville",
"aksu-zhabagly": "Shymkent",
"al-wahbah-crater": "Taif",
"ala-archa": "Bishkek",
"aletsch": "Brig",
"altyn-emel": "Almaty",
"annapurna": "Pokhara",
"aukstaitija": "Ignalina",
"azraq": "Azraq",
"bako": "Kuching",
"banco-national-park": "Abidjan",
"bardia": "Thakurdwara",
"batad": "Banaue",
"blyde-river-canyon": "Graskop",
"bokor": "Kampot",
"bryce-canyon": "Bryce Canyon City",
"bwabwata": "Divundu",
"cajas": "Cuenca",
"charyn": "Almaty",
"chinhoyi": "Chinhoyi",
"chitwan": "Sauraha",
"chobe": "Kasane",
"colca": "Chivay",
"congo-nile-trail": "Gisenyi",
"copper-canyon": "Creel",
"dambulla": "Dambulla",
"dana": "Dana",
"darvaza": "Ashgabat",
"day-forest": "Tadjoura",
"debed-canyon": "Alaverdi",
"djoudj": "Saint-Louis",
"ellora": "Aurangabad",
"everest-base-camp": "Lukla",
"fazao": "Sokode",
"fish-river-canyon": "Keetmanshoop",
"fort-portal": "Fort Portal",
"franz-josef": "Franz Josef",
"galicica": "Ohrid",
"garden-route": "Knysna",
"gauja": "Sigulda",
"gesause": "Admont",
"glacier-montana": "Whitefish",
"gobi": "Dalanzadgad",
"gola": "Kenema",
"gonarezhou": "Chiredzi",
"grand-canyon": "Flagstaff",
"great-ocean-road": "Apollo Bay",
"ha-giang": "Ha Giang",
"ha-kome": "Maseru",
"hlane": "Manzini",
"hoge-veluwe": "Arnhem",
"hustai": "Ulaanbaatar",
"hwange": "Victoria Falls",
"inca-trail": "Cusco",
"isalo": "Ranohira",
"ivindo": "Makokou",
"jirisan": "Gurye",
"kafue": "Lusaka",
"kakadu": "Jabiru",
"kakum": "Cape Coast",
"karijini": "Tom Price",
"kemeri": "Jurmala",
"khama-rhino": "Serowe",
"kings-canyon": "Alice Springs",
"kissama": "Luanda",
"kong-lor": "Thakhek",
"krka": "Sibenik",
"kruger": "Nelspruit",
"lake-mburo": "Mbarara",
"liwonde": "Liwonde",
"loango": "Port-Gentil",
"lompoul": "Dakar",
"longji": "Longsheng",
"lope": "Lope",
"lovcen": "Kotor",
"lut-desert": "Kerman",
"majete": "Blantyre",
"manaslu": "Kathmandu",
"martvili": "Kutaisi",
"masoala": "Maroantsetra",
"matka-canyon": "Skopje",
"mayumba": "Mayumba",
"mgahinga": "Kisoro",
"mikumi": "Mikumi",
"mkhaya": "Manzini",
"mlawula": "Manzini",
"mole-national-park": "Tamale",
"moremi": "Maun",
"mulu": "Miri",
"namibe": "Namibe",
"ngorongoro": "Karatu",
"niokolo-koba": "Tambacounda",
"nkhotakota": "Nkhotakota",
"nyerere": "Dar es Salaam",
"outamba-kilimi": "Makeni",
"pacaya": "Antigua Guatemala",
"pallas-yllas": "Muonio",
"pamir": "Khorog",
"peak-district": "Castleton",
"pongara": "Libreville",
"poon-hill": "Pokhara",
"postojna": "Postojna",
"qasr-amra": "Amman",
"queen-elizabeth": "Kasese",
"quilotoa": "Latacunga",
"retezat": "Hateg",
"rishikesh": "Rishikesh",
"ruaha": "Iringa",
"rugova": "Peja",
"sajama": "La Paz",
"salkantay": "Cusco",
"sani-pass": "Underberg",
"santa-cruz-trek": "Huaraz",
"sg-sungei-buloh": "Singapore",
"skazka": "Bokonbaevo",
"skocjan-caves": "Divaca",
"slowinski": "Leba",
"somoto": "Somoto",
"sutjeska": "Foca",
"tacugama": "Freetown",
"tai-national-park": "San-Pedro",
"tara": "Bajina Basta",
"tara-canyon-montenegro": "Zabljak",
"tatacoa": "Villavieja",
"terelj": "Ulaanbaatar",
"thakhek": "Thakhek",
"thy": "Thisted",
"una-national-park": "Bihac",
"utah-parks": "Springdale",
"uvac": "Nova Varos",
"vieng-xai": "Sam Neua",
"virachey": "Banlung",
"volcanoes-rwanda": "Musanze",
"waitomo": "Waitomo",
"wenchi": "Ambo",
"white-desert": "Bawiti",
"yala": "Tissamaharama",
"yangykala": "Balkanabat",
"yoho": "Golden",
"zemaitija": "Plunge",
"ziwa": "Masindi"
};
