// What Explore shows before anyone searches or filters: the most visited countries,
// and for each country its best-known places. Every other country and place is one
// click away ("Show all countries", "See all locations"). Countries not listed in
// POPULAR_PLACES fall back to their first few places.
window.POPULAR_COUNTRIES = [
  "thailand", "vietnam", "indonesia", "japan", "cambodia", "laos", "philippines", "malaysia",
  "india", "nepal", "sri-lanka", "south-korea", "china", "taiwan", "singapore",
  "portugal", "spain", "france", "italy", "greece", "croatia", "uk", "ireland", "germany",
  "netherlands", "czechia", "hungary", "austria", "switzerland", "iceland", "norway", "poland",
  "albania", "georgia", "turkey",
  "morocco", "egypt", "jordan", "uae", "south-africa", "kenya", "tanzania",
  "mexico", "guatemala", "costa-rica", "cuba", "colombia", "peru", "bolivia", "ecuador",
  "argentina", "chile", "brazil", "usa", "canada",
  "australia", "new-zealand"
];

window.POPULAR_PLACES = {
  thailand: ["bangkok", "chiang-mai", "phuket", "koh-phi-phi", "pai", "railay"],
  vietnam: ["hanoi", "ha-long-bay", "hoi-an", "saigon", "ha-giang", "ninh-binh"],
  indonesia: ["ubud", "yogyakarta", "nusa-penida", "gili-air", "labuan-bajo", "bromo"],
  japan: ["tokyo", "kyoto", "osaka", "hiroshima", "nara", "kanazawa"],
  cambodia: ["siem-reap", "phnom-penh", "kampot", "koh-rong-samloem"],
  laos: ["luang-prabang", "vang-vieng", "nong-khiaw", "si-phan-don"],
  philippines: ["el-nido", "siargao", "coron", "bohol", "moalboal", "manila"],
  malaysia: ["kuala-lumpur", "penang", "melaka", "cameron", "perhentian"],
  india: ["delhi", "agra", "jaipur", "udaipur", "varanasi", "mumbai"],
  nepal: ["kathmandu", "pokhara", "everest-base-camp", "annapurna", "chitwan"],
  "sri-lanka": ["kandy", "ella", "sigiriya", "galle", "mirissa"],
  "south-korea": ["seoul", "busan", "gyeongju", "jeju"],
  china: ["beijing", "shanghai", "xian", "chengdu", "yangshuo", "hong-kong"],
  taiwan: ["taipei", "taroko", "jiufen", "tainan"],
  singapore: ["sg-city", "sg-chinatown", "sg-little-india"],
  portugal: ["lisbon", "porto", "sintra", "algarve", "madeira"],
  spain: ["barcelona", "madrid", "seville", "granada-spain", "valencia-spain", "san-sebastian"],
  france: ["paris", "nice", "lyon", "provence", "chamonix", "bordeaux"],
  italy: ["rome", "florence", "venice", "cinque-terre", "amalfi-coast", "naples"],
  greece: ["athens", "santorini", "naxos", "crete", "meteora"],
  croatia: ["split", "dubrovnik", "plitvice", "hvar", "zagreb"],
  uk: ["london", "edinburgh", "skye", "lake-district", "york", "bath"],
  ireland: ["dublin", "galway", "cliffs-of-moher", "dingle", "kerry"],
  germany: ["berlin", "munich", "hamburg", "cologne", "fussen"],
  netherlands: ["amsterdam", "utrecht", "rotterdam", "haarlem"],
  czechia: ["prague", "cesky-krumlov", "kutna-hora", "brno"],
  hungary: ["budapest", "eger", "balaton"],
  austria: ["vienna", "salzburg", "hallstatt", "tyrol"],
  switzerland: ["lucerne", "interlaken", "zermatt", "lauterbrunnen", "zurich"],
  iceland: ["reykjavik", "golden-circle-iceland", "south-coast", "snaefellsnes"],
  norway: ["oslo", "bergen", "lofoten", "tromso", "flam"],
  poland: ["krakow", "warsaw", "gdansk", "zakopane", "wroclaw"],
  albania: ["tirana", "berat", "ksamil", "theth", "gjirokaster"],
  georgia: ["tbilisi", "kazbegi", "mestia", "batumi", "kutaisi"],
  turkey: ["istanbul", "cappadocia", "pamukkale", "ephesus", "fethiye", "antalya"],
  morocco: ["marrakech", "fes", "chefchaouen", "merzouga", "essaouira"],
  egypt: ["cairo", "giza", "luxor", "aswan", "dahab", "alexandria"],
  jordan: ["petra", "wadi-rum", "amman", "dead-sea-jordan", "aqaba"],
  uae: ["dubai", "abu-dhabi", "sharjah"],
  "south-africa": ["cape-town", "garden-route", "kruger", "johannesburg", "drakensberg"],
  kenya: ["nairobi", "maasai-mara", "diani", "lamu", "amboseli"],
  tanzania: ["zanzibar", "serengeti", "ngorongoro", "kilimanjaro", "arusha"],
  mexico: ["cdmx", "oaxaca", "merida-mexico", "san-cristobal", "holbox", "puerto-escondido"],
  guatemala: ["antigua", "atitlan", "flores", "tikal", "semuc"],
  "costa-rica": ["la-fortuna", "monteverde", "manuel-antonio", "puerto-viejo", "santa-teresa-costa-rica"],
  cuba: ["havana", "vinales", "trinidad-cuba", "cienfuegos"],
  colombia: ["cartagena", "medellin", "bogota", "salento", "tayrona", "guatape"],
  peru: ["cusco", "machu-picchu", "lima", "arequipa", "huacachina", "puno"],
  bolivia: ["la-paz", "uyuni", "sucre", "copacabana-bolivia"],
  ecuador: ["quito", "galapagos", "banos", "cuenca", "quilotoa"],
  argentina: ["buenos-aires", "mendoza", "bariloche", "el-calafate", "el-chalten", "puerto-iguazu"],
  chile: ["santiago-chile", "valparaiso", "atacama", "torres-del-paine", "pucon"],
  brazil: ["rio", "iguacu", "salvador", "ilha-grande", "paraty", "florianopolis"],
  usa: ["new-york", "san-francisco", "new-orleans", "grand-canyon", "yosemite", "chicago"],
  canada: ["vancouver", "banff", "montreal", "toronto", "quebec-city", "jasper"],
  australia: ["sydney", "melbourne", "great-barrier-reef", "uluru", "byron-bay", "tasmania"],
  "new-zealand": ["queenstown", "auckland", "rotorua", "tongariro", "milford", "wanaka"],
  // Less visited countries: the places most first-timers go.
  oman: ["muscat", "nizwa", "wahiba", "wadi-shab"],
  iran: ["isfahan", "yazd", "shiraz", "tehran", "kashan"],
  uzbekistan: ["samarkand", "bukhara", "khiva", "tashkent"],
  kyrgyzstan: ["bishkek", "karakol", "song-kul", "osh"],
  mongolia: ["ulaanbaatar", "gobi", "khovsgol", "terelj"],
  slovenia: ["ljubljana", "bled", "piran", "soca"],
  montenegro: ["kotor", "budva", "durmitor", "perast"],
  bosnia: ["sarajevo", "mostar", "blagaj"],
  romania: ["bucharest", "brasov", "sibiu", "cluj-napoca", "sighisoara"],
  bulgaria: ["sofia", "plovdiv", "veliko-tarnovo", "rila"],
  belgium: ["brussels", "bruges", "ghent", "antwerp"],
  denmark: ["copenhagen", "aarhus", "skagen"],
  sweden: ["stockholm", "gothenburg", "abisko", "malmo"],
  finland: ["helsinki", "lapland", "turku"],
  malta: ["valletta", "gozo", "mdina"],
  namibia: ["sossusvlei", "swakopmund", "etosha", "windhoek"],
  ethiopia: ["addis", "lalibela", "simien", "gondar"],
  madagascar: ["antananarivo", "andasibe", "morondava", "isalo", "nosy-be"],
  tunisia: ["tunis", "sidi-bou-said", "djerba", "el-jem", "tozeur"],
  panama: ["panama-city", "bocas", "san-blas", "boquete"],
  nicaragua: ["granada", "leon", "ometepe", "san-juan-del-sur"],
  belize: ["caye-caulker", "san-ignacio", "placencia", "hopkins"],
  fiji: ["nadi", "yasawas", "mamanuca", "taveuni"],
  maldives: ["maafushi", "thoddoo", "ukulhas", "dhigurah"]
};
